CordovaLib/Classes/CDVWebViewDelegate.m

Currently, the code sets `_state` immediately before creating the string to log, so it will always print "CDVWebViewDelegate: Navigation started when state=1". This change just moves setting `_state` to after the log statement.

Change _state after creating logging string

---

bin/templates/scripts/cordova/build.bat
bin/templates/scripts/cordova/log.bat
bin/templates/scripts/cordova/run.bat

Just output a warning for ios project scripts on windows

CB-8772 ios bin scripts are nonexecutable on Windows

---

CordovaLib/Classes/CDVWebViewDelegate.m

Blob schemes won't load in iframes, even though blob:* is whitelisted.
This is needed for special cases, like when using an epub reader ([ePub.js](https://github.com/futurepress/epub.js/)), that downloads an epub, extracts it to a blob and displays it in an iframe.
This currently works perfectly in cordova-android, but not in cordova-ios.
I've debugged why it happens... the Whitelists says the scheme is allowed and the URL is allowed, but then
```Objective-C
[NSURLConnection canHandleRequest]
```
returns false, thus cancelling the request. Hardcoding "blob" as an allowed scheme (like it's currently done with mailto, tel and sms) fixes this issue.

CB-9558 Blob schemes won't load in iframes

---

.gitattributes

Updates gitattributes to common web project template to help git recognize binary files
[Jira issue](https://issues.apache.org/jira/browse/CB-9836)

CB-9836 Add .gitattributes to prevent CRLF line endings in repos

---

bin/lib/check_reqs.js
bin/templates/scripts/cordova/lib/run.js

Currently when running `cordova run ios --device` the app gets deployed two times via usb and wifi. But when disconnecting from USB it is not possible to deploy at all, so the deployment fails. This issue is related to phonegap/ios-deploy#170 and disables this behavior to get the deployment working again, when using usb.

Disable ios-deploy wifi mode when deploying to a device

---

package.json

This issue seems to have been introduced by a change in simctl, which ios-sim relies on:
https://github.com/phonegap/simctl/commit/34426c719130a73b83af65f50a11a46267a5ad0b

CB-10912: update ios-sim to 5.0.7 to fix 'Invalid Device State' errors

---

bin/templates/scripts/cordova/lib/prepare.js

The 60x60 icon is not used in `AppIcon` catalog and has been removed in 68af7ea. However if you have `<icon width="60" height="60" ...>` in `config.xml` it'll be added to catalog as `icon-60.png`. This will result in Xcode warning `The app icon set "AppIcon" has an unassigned child`
See also [CB-11475](https://issues.apache.org/jira/browse/CB-11475)

CB-11475 Ignore unsupported 60x60 icon

---

CordovaLib/Classes/Public/CDVUserAgentUtil.m

Adds app version to the list of items that invalidates the cached user agent.

CB-10078 fixed by refreshing cached userAgent on version bump

---

bin/templates/scripts/cordova/build
bin/templates/scripts/cordova/lib/build.js
tests/CordovaLibTests/CordovaLibTests.xcodeproj/project.pbxproj

Background info on the mailing list: https://lists.apache.org/thread.html/85a715681471c774821d76a90ec288943eca1a4bb0a267ba299d2eb3@%3Cdev.cordova.apache.org%3E
Mostly just opened for review now, and getting any feedback or comments. Tests will probably fail, and will be updated after review.
A note that using xcodebuild for exporting the archive requires using the system installation of Ruby, so if you're an RVM user then you'll need to `rvm use system` first. I'm looking to see if there's a way we can work around this.
/cc @shazron

CB-11860 - Update packaging strategy for Xcode 8

---

.travis.yml

This closes #323
iOS
Adds node 4.x and 6.x run to Travis CI
See Travis build just under this PR

CB-12960 Run tests on Node 4.x and 6.x

---

CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewDelegate.m
tests/CordovaLibTests/CDVWebViewDelegateTests.m

iOS
Fix the navigations that starts with the STATE_WAITING_FOR_LOAD_START  by calling the self webview:didFailLoadWithError method instead of delegating it.

CB-13093: (iOS) Infinite looping when stressing navigation

---

bin/templates/scripts/cordova/lib/prepare.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/fixtures/ios-config-xml/CordovaLib/CordovaLib.xcodeproj/project.pbxproj
tests/spec/unit/fixtures/ios-config-xml/SampleApp.xcodeproj/project.orig.pbxproj
tests/spec/unit/fixtures/ios-config-xml/SampleApp.xcodeproj/project.pbxproj
tests/spec/unit/fixtures/ios-config-xml/SampleApp/.gitignore
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Bridging-Header.h
tests/spec/unit/fixtures/ios-config-xml/SampleApp/CDVLaunchScreen.storyboard
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Classes/AppDelegate.h
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Classes/AppDelegate.m
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Classes/MainViewController.h
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Classes/MainViewController.m
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Classes/MainViewController.xib
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Entitlements-Debug.plist
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Entitlements-Release.plist
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Images.xcassets/LaunchStoryboard.imageset/Contents.json
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Plugins/README
tests/spec/unit/fixtures/ios-config-xml/SampleApp/SampleApp-Info.plist
tests/spec/unit/fixtures/ios-config-xml/SampleApp/SampleApp-Prefix.pch
tests/spec/unit/fixtures/ios-config-xml/SampleApp/config.xml
tests/spec/unit/fixtures/ios-config-xml/SampleApp/main.m
tests/spec/unit/prepare.spec.js

Added new ios-config-xml project fixture based off cordova-ios@4.4.0 template. The old one doesn't reflect current project structure.
Added failing test for multiple adds of the same `<resource-file>` tag
Fixed failing test in prepare.js
Fix failing test due to new ios-config-xml project template in addPlugin
Don't need to prefix 'Resources' and 'Plugins' to the files that are from those groups. The file reference 'sourceTree' relies on its parent group, in the new template structure.
self
Fix multiple file references added for a `<resource-file>` tag. This creates "cordova build" failures.
npm run unit-tests
npm test

CB-13112 - <resource-file> should not create a new file reference on each "cordova prepare"

---

CordovaLib/Classes/Private/Plugins/CDVLogger/CDVLogger.h
CordovaLib/Classes/Private/Plugins/CDVLogger/CDVLogger.m
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/cordova.js
bin/templates/project/__PROJECT_NAME__/config.xml
bin/templates/scripts/cordova/defaults.xml
cordova-js-src/platform.js
cordova-js-src/plugin/ios/console.js
cordova-js-src/plugin/ios/logger.js

Adds support for `window.console` to be built in to generated cordova-ios projects. Essentially: sunsetting [cordova-plugin-console](https://github.com/apache/cordova-plugin-console) and integrating its iOS bits into cordova-ios.
- added native source files for CDVLogger
- updated pbxproj file for CordovaLib to take the new files into account
NOTE: this PR requires the use of latest master of cordova-js.
Just `npm test` locally on my Mac. Unsure if I should add any additional tests? @shazron leaning on you for guidance on that question.

CB-13164: Integrated cordova-plugin-console

---

CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewNavigationDelegate.m

…eceived on didFailLoadWithError
iOS
Prevent the infinite loop when a NSURLErrorCancelled is received

CB-13222 - (iOS) Infinite Loop when a "NSURLErrorCancelled -999" is received on didFailLoadWithError

---

bin/templates/scripts/cordova/lib/prepare.js
tests/spec/unit/prepare.spec.js

Self
Fixes access tag writing of the wrong key NSAllowsArbitraryLoadsInMedia. It should be NSAllowsArbitraryLoadsForMedia
Fixes unit-test errors that were not caught since the exceptions were thrown in a Promise (about 30 errors)
npm run unit-tests
npm run eslint

CB-13210 - App Transport Security Key is wrong

---

bin/templates/project/__PROJECT_NAME__/Images.xcassets/AppIcon.appiconset/Contents.json
bin/templates/scripts/cordova/lib/prepare.js

iOS
Adds support for the marketing icon. This is required for app submission since XCode 9.
Ran `cordova prepare` and made sure that the icon referenced from `config.xml`gets properly added and is displayed in XCode.

CB-13191: (ios) Support marketing icon

---

bin/templates/project/__PROJECT_NAME__/Images.xcassets/AppIcon.appiconset/Contents.json
bin/templates/scripts/cordova/lib/prepare.js

iOS
Updates the mapped icons to include newer devices and screen resolutions
Added all available icons to a project, opened in Xcode and checked the Images.xcassets file to make sure all icons were included.

CB-12896: (ios) Update icon mapping

---

bin/templates/project/__PROJECT_NAME__/Images.xcassets/LaunchImage.launchimage/Contents.json
bin/templates/scripts/cordova/lib/prepare.js

iOS
Adds splash screen support for iPhone X and other missing devices.
Created a project with all supported splash screens, opened in Xcode and viewed the Images.xcassets to see that the splash screens were correctly added.

CB-13290: (ios) Update splash screen mapping for missing devices

---

bin/templates/project/__PROJECT_NAME__/CDVLaunchScreen.storyboard

iOS
Adjust Constrains of the launchscreen storyboard. LaunchScreen storyboard constraints were never updated for ios11/iphoneX. This can cause the splashscreen to jump during startup (see GIF in issue).
Manual/visual test

CB-13505: (ios) adjust constraint for launchscreen storyboard

---

bin/templates/scripts/cordova/build
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/run
tests/spec/unit/build.spec.js

iOS with Xcode 9
This adds a `automaticProvisioning` option to the build config which passes flags to xcodebuild during the exporting step that allow it to automatically create and update provisioning profiles for automatic code signing.
I don't love that we're adding even more random stuff to the build config, but I suspect most people don't want this to be enabled by default.
Added a case to existing spec tests.
Tested with a Cordova project at work and confirmed to be working.

CB-13523: Add flag for Xcode-managed provisioning

---

CordovaLib/Classes/Public/CDVViewController.m

iOS
Removed `[pasteboard setValue:string forPasteboardType:@"public.text"]` clipboard workaround, which is not need in iOS 11, but breaking copy/past functionality from outside the app (i.e notes/safari) into (Cordova) consumer app using native UI as well.
Manually tested copy/pastes functionality for both cordova (web UI) components as well as with native UI in a container app.

CB-13510: (iOS) Removed clipboard workaround, which was braking copy/paste functional iOS 11

---

bin/templates/scripts/cordova/Api.js

CB-12582
Cordova iOS 4.5.4
Fix the pod install plugin (plugin with podspec framework) to work.
For example, phonegap-plugin-push plugin with `GoogleService-Info.plist`
(in config.xml, `<resource-file src="GoogleService-Info.plist" />` is added)
The case, 
```
cordova platform add ios@4.5.4
cordova plugin add phongegap-plugin-push
cordova prepare
cordova compile --device
```
works well.
The case, 
```
cordova plugin add phonegap-plugin-push
cordova platform add ios@4.5.4
cordova prepare
cordova compile --device
```
does not work becuase the cordova overwrite project.pbxproj which is changed by pod install. 
This pull request fixes this issue.
Do in my local environment with cordova-ios 4.5.4

CB-12582: exec purgeProjectFileCache when pod install

---

CordovaLib/Classes/Public/CDVViewController.m

iOS
Fixes a bug that prevents (Swift) plugins from being instantiated when running in Xcode 9/Swift 4.
Local verification with Xcode 9.2.

CB-13824: (ios) Swift 4 support

---

bin/templates/scripts/cordova/lib/build.js
tests/spec/unit/build.spec.js

iOS
Passes `-allowProvisioningUpdates` to the build/archive step. We are already passing it to the export step (https://github.com/apache/cordova-ios/pull/347) but it's also worth having it here.
Testing on Ayogo's Jenkins instance and was able to successfully make an iOS build without any manual steps to set up certificates or provisioning profiles.

CB-13523: Pass automaticProvisioning to build step

---

CordovaLib/Classes/Private/Plugins/CDVGestureHandler/CDVGestureHandler.m

https://issues.apache.org/jira/browse/CB-14039
When users try to disable webview magnifying glass by using `<preference name="Suppresses3DTouchGesture" value="true" />`
The inputs are clickable and the user can write.
The inputs are not clickable and the user cannot write
Note: Sometimes the application opens the keyboard, but it's really difficult to get.
Create a new project: phonegap create myApp
Add some inputs type text in the HTML
Run the application: phonegap run ios
Issue was related with `<preference name="Suppresses3DTouchGesture" value="true" />`
This option was using extremely low value of minimumPressDuration that was suppressing onClick events etc. After experimenting on Iphone SE and Iphone 7 and simulators I found that values 0.15f do not interfere with onClick handlers. …

 CB-14039: Inputs type text don't work on iOS

---

CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewEngine.m

Attempts to use `CDVWebViewEngineProtocol::updateWithInfo` to set a new `UIWebViewDelegate` were not working; instead of setting the passed in delegate, it was setting the `CDVViewController` instance as the delegate instead.
cordova-ios
This commit fixes the `CDVWebViewEngine` class so that the proper delegate is ultimately passed in to the `UIWebView` when calling `updateWithInfo`.
I used the code to create a new test app, to which I applied a test plugin which attempts to set the `UIWebViewDelegate`. I verified that I was able to successfully set the delegate, and receive the events from the `UIWebView`.
I also ran `npm test` and verified all tests passed.

CB-14076: (ios) Setting UIWebViewDelegate on CDVWebViewEngineProtocol doesn't work

---

CordovaLib/Classes/Public/CDVViewController.m
tests/CordovaLibTests/CDVViewControllerTest.m

Hi!
We've stumbled on a similar issue to this: https://issues.apache.org/jira/browse/CB-14045 although for us it takes a bit longer (10h or so of app being in background).
In our case the app resumes in a half working state, where the web view has been reinitialised pointing to about:blank with only default Js api available and no cordova js. Then, cordova tries to emit those resume and other events but all of them fail as there is no cordova js var available.
this approach does not fix app getting into that state as I am not fully aware how does it do that (12h debugging cycle is pretty hard).. but it gets it out of the broken state by pointing the webview back to the app's url.
what do you think?
Thanks!

CB-14045 - reinit url after app freezes

---

package.json

iOS
Removes devDependencies no longer needed from `package.json`:
- `coffee-script` (package name was deprecated in favor of `coffeescript`)
- `uncrustify`
~~includes plist@3 update proposed in #367~~
- `npm run unit-tests` passes
- starter project from `cordova create` with iOS platform added by `cordova platform add https://github.com/brodybits/cordova-ios#dev-dep-cleanup` runs on iOS simulator
- `npm test` stages passing on Travis CI in this PR
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

package.json cleanup devDependencies

---

.travis.yml
appveyor.yml

iOS
Enable AppVeyor CI & Travis CI testing on Node.js versions 8 & 10.
These changes passed on AppVeyor CI & Travis CI in a WIP PR.
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

CI testing on Node.js versions 8 & 10

---

bin/templates/scripts/cordova/lib/run.js

cordova-ios
The command `cordova run ios --simulator` does not finish properly.
Because bin/templates/scripts/cordova/lib/run.js opens ios simulator by calling
```
iossim.launch(appPath, 'com.apple.CoreSimulator.SimDeviceType.' + target, logPath, '--exit');
```
Dut to the last argument `--exit`, ios-sim module will call `process.exit(0);` in ios-sim/src/lib.js.
Then the cordova command itself stops. 
This PR improves the issue.
By using child_process, the cordova command does not stop when ios-sim calls `process.exit(0)`.
Here is sample plugin. https://github.com/knight9999/cordova-plugin-promise-sample .
This plugin has a `after run` plugin hook.
This plugin shows following messages after the command `cordova run ios --emulator`.
```
--- start run ---
--- now count = 0 ---
--- now count …
```

CB-13581 open ios simulator by using child_process

---

package.json

iOS
- pin some more bundled dependencies to clear the red highlights in `npm outdated --depth=0`
- `npm audit` with npm@6.2.0 (latest version) shows 0 vulnerabilities
- `npm i && npm t` passes on the following Node.js versions: deprecated Node.js 4 (npm 2.15.11), Node.js 6.14.3 (npm 3.10.10), Node.js 8.11.3 (npm 5.6.0), Node.js 10.7.0 (npm 6.1.0)
- using `cordova platform add brodybits/cordova-ios#cb-14145-pin-more-added-bundled-deps-in-patch-only` to add platform to new Cordova project and test on iOS simulator using `cordova run ios` succeeds on the following Node.js versions:
- deprecated Node.js 4 (npm 2.15.11)
- Node.js 8 (npm 5.6.0)
__CI testing:__
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" …

CB-14145 pin more added bundled dependencies in 4.5.x only

---

bin/templates/scripts/cordova/lib/versions.js

iOS
While working on an upcoming PR (#377 ) for improving the test coverage, I noticed that the `get_apple_osx_version` method has been returning `undefined`. 
After further investigation, the RegEx pattern has been looking for OSX SDK version `OS X` no longer exists since Xcode 8+ 
Example print outs:
**Xcode 7.3:** https://travis-ci.org/erisu/macos-test/jobs/395785417
**Xcode 8:** https://travis-ci.org/erisu/macos-test/jobs/395785418
**For other versions:** https://travis-ci.org/erisu/macos-test/builds/395785415
From the above print out, I determined that the RegEx pattern should be updated to `macOS`
- https://travis-ci.org/erisu/cordova-ios/builds/395835801
- https://ci.appveyor.com/project/erisu/cordova-ios/build/1.0.3
**Note:** Oddly Node 4 appears to be failing but I have submitted …

Fixed Get Apple OSX Version method

---

appveyor.yml

iOS
- Simplify installation on AppVeyor CI now that `uncrustify` is gone, should now succeed on deprecated Node.js 4 version
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~
- ~~Added automated test coverage as appropriate for this change.~~

Simplify installation on AppVeyor CI

---

tests/spec/unit/versions.spec.js

iOS
- cover apple version functions in spec, as needed to cover the GH-376 update that I already merged into `master`
(was part of GH-377 by @erisu)
- ~~[Reported an issue](http://cordova.apache.org/contribute/issues.html) in the JIRA database~~
- ~~Commit message follows the format: "CB-3232: (android) Fix bug with resolving file paths", where CB-xxxx is the JIRA ID & "android" is the platform affected.~~

spec cover apple version functions (covers GH-376 update)

---

.travis.yml
appveyor.yml
package.json

iOS
- Drops Node 4 from travis and appveyor
- Increase the engine requirement of node in package.json
- Added engineStrict to package.json. (Match with other platforms e.g cordova-android)
- Cleanup .travis.yml
- https://travis-ci.org/erisu/cordova-ios/builds/395831324
- https://ci.appveyor.com/project/erisu/cordova-ios/build/1.0.1

CB-14074 ios: Remove Node 4 support from CI & package.json

---

package.json

ios (tests)
This PR fixes the recent test failures on `master` branch. 
These tests are failing because of the latest `Jasmine@3.2.0` that has been released within the past 2 days. (https://github.com/jasmine/jasmine-npm/releases/tag/v3.2.0)
At the time the original PR was submitted and tested, Jasmine was at version `3.1.0`. On this version, all tests were passing. https://travis-ci.org/apache/cordova-ios/builds/412472891
By pinning Jasmine@3.1.0 in `package.json`, the tests will continue to pass.
- local `npm test`
- Travis CI: https://travis-ci.org/erisu/cordova-ios/builds/414529064
- AppVeyor: https://ci.appveyor.com/project/erisu/cordova-ios/build/1.0.34

Pin jasmine@3.1.0

---

bin/templates/scripts/cordova/lib/prepare.js

iOS
When copying a resource-file to a target that already exists, don't add it to the xcodeproj file a second time.
My particular scenario is that I wanted to overwrite CDVLaunchScreen.storyboard and it was getting added to the xcodeproj twice and causing weird failures.

CB-14141: Don't duplicate resource files in xcodeproj

---

bin/templates/scripts/cordova/lib/build.js
tests/spec/unit/build.spec.js

ios
- Remove xcconfig build flag for device and emulator.
- Remove custom argument override for xcconfig.
- Updated build test spec with removal of xcconfig with cleanup.
Since Cordova projects are using `xcworkspace` and the `content.xcworkspacedata` file declares our projects `xcodeproj`, the `xcconfig` file paths are declared in the `pbxproj`.
*contents.xcworkspacedata*
```
<FileRef location = "group:HelloCordova.xcodeproj"></FileRef>
```
Once a Pod project is added to the application, for example `cordova-plugin-firebase-messaging`,  the `contents.xcworkspacedata` file is updated to reflect the Pod project.
```
<FileRef location = "group:HelloCordova.xcodeproj"></FileRef>
<FileRef location = "group:Pods/Pods.xcodeproj"></FileRef>
```
If the xcconfig flag was set, in this scenario, …

Removal of xcconfig build flag

---

tests/spec/unit/build.spec.js
tests/spec/unit/prepare.spec.js

Ensures logging events aren't printed to the screen during jasmine test runs.

Silence logging output during test runs

---

bin/templates/scripts/cordova/lib/list-emulator-build-targets

Successor of https://github.com/apache/cordova-ios/pull/428, ready for XCode 10.1 release.
iOS
Fix scanning for available emulators to build / run against.
Tests have been run on a Mac mini with Mac OS X Mojave 10.14 and Xcode 10.1.

iOS: Fix running cordova build ios for emulators with Xcode 10.1 RELEASE

---

bin/create
bin/lib/create.js

ios
When platform is installed though CLI, `cordova platform add android`, the copy node_modules step is no longer valid as dependencies are now at the project level.
The step is required only when the create binary from the platform repo is called.
https://github.com/apache/cordova/issues/32
- npm t
- https://ci.appveyor.com/project/erisu/cordova-ios/builds/20107772
- https://travis-ci.org/erisu/cordova-ios

Only copy platform node_modules when create by bin

---

tests/spec/unit/prepare.spec.js

**Note:** This can't be merged until we do a release of cordova-common next major and update the dependency in cordova-ios package.json. But I'm opening this now so it's ready to go whenever that process happens.
iOS, but it's unit testing so technically none
Fixes the unit tests when run against cordova-common master (which uses `fs-extra`)
Unit tests now pass.

Fix unit tests against cordova-common@3

---

bin/templates/scripts/cordova/lib/list-emulator-build-targets

After updating to macOS 10.14.2, running `cordova run ios` causes error `Cannot read property 'name' of undefined`. It turns out that the problem is due to `device.name` including the '-'. It seems this changed with the update to Xcode 10.1 which seems to have been bundled along with the 10.14.2 update.

Fix issue after updating to macOS 10.14.2.

---

bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/clean.js
bin/templates/scripts/cordova/lib/run.js
bin/templates/scripts/cordova/lib/spawn.js

iOS
Applies `superspawn` and `shelljs` consistently. Both modules are used in other places in this module. The existing `spawn.js` in this project should be obsolete now. I preserved it just in case.
**Details by @brodybits:**
Change details:
* Use `cross-spawn` ("superspawn") instead of `child-process` spawn
* Use `shelljs` instead instead of `child-process` spawn in other places
* Add a comment that the `spawn` function provided by `spawn.js` is deprecated
Motivation: this change will allow us to spawn with `printCommand: true` option, to print the `xcodebuild` and other shell commands as proposed in #479.
~~Nothing at all.~~

Use cross-spawn & shelljs instead of child-process

---

bin/create
bin/lib/create.js

ios
- Reverts PR #456 (Only copy platform node_modules when created by binary)
- Replace implementation to copy the platform node_modules only when the folder exists.
https://github.com/apache/cordova/issues/32
- npm run eslint
- npm run unit-tests

Copy node_modules if the directory exists

---

bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/clean.js
bin/templates/scripts/cordova/lib/run.js

iOS
It logs the CLI for `xcodebuild`. Please note that this PR expects #477 to be merged also.
None

emit xcodebuild & other spawned CLI commands

---

CordovaLib/Classes/Public/CDVViewController.m
tests/CordovaLibTests/CDVViewControllerTest.m

Fix for [CB-14045](https://issues.apache.org/jira/browse/CB-14045) (reinit url after app freezes) was mistakenly raised on 4.5.x in PR #363, merged on 4.5.x, reverted, then merged on `master`.
I think this fix should have also been part of 4.5.x.
I am raising this PR just in case we do another cordova-ios@4.5.x patch release.
The commit ID on `master` is: 6e790afb0e8e7e6e427960b6e884462dc981744f

CB-14045 - reinit url after app freezes on 4.5.x

---

bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/clean.js
bin/templates/scripts/cordova/lib/run.js

iOS
It restores the `stdio` setting that was previously applied through the `spawn.js` shell execution utility.
In the current setting, previously visible console output would likely be hidden from the user.
None

Restore stdio passthrough behavior

---

tests/spec/component/versions.spec.js

iOS
It makes sure that the tests are failed correctly if the result is not as expected. Previously, these tests would simply time out after the Jasmine default timeout period. Now the tests will fail right away and give a better indication towards the reason.
I've ran the tests.
```shell
Started
....F
Failures:
1) versions get_tool_version method should find pod version.
Message:
Failed: expected promise resolution
Stack:
Error: expected promise resolution
at versions.get_tool_version.then.catch (/Users/oliver/cordova-ios/tests/spec/component/versions.spec.js:61:37)
```

Ensure test failure on unexpected promise resolution

---

bin/templates/scripts/cordova/lib/PodsJson.js

iOS
Fix an error in de the code (which can be seen through understanding the code logic)
My cordova project did not install certain pods.
After making this change, the pods were installed.

PodsJson.increment/decrement has a code error resulting in pods not being installed while specified

---

bin/templates/scripts/cordova/lib/list-devices
tests/spec/unit/lib/list-devices.spec.js

iOS
I'm using Virtualhere (https://www.virtualhere.com/home) for developing remotely.
While Safari and Xcode do see the device after connecting via Virtualhere, cordova does not.
The attached patch remedies the issue in cordova-ios@4.5.5
Manual testing with virtualhere devices as well as regular USB devices
closes #458

cordova run --list --device fails for Virtualhere devices (fixes #458)

---

.travis.yml
CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVIntentAndNavigationFilter.m
CordovaLib/Classes/Public/CDVAppDelegate.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/CordovaLib.xcodeproj/project.xcworkspace/contents.xcworkspacedata
CordovaLib/CordovaLib.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
CordovaLib/CordovaLib.xcodeproj/xcshareddata/xcschemes/Cordova.xcscheme
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaFrameworkApp.xcscheme
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaLib.xcscheme
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaLibApp.xcscheme
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaLibTests.xcscheme

iOS
Upgrades CordovaLib.xcodeproj to Xcode 10 standards
All the objc unit tests pass locally with Xcode 10.1, opening this PR to see how they are handled by Xcode 9.

CordovaLib.xcodeproj file upgraded for Xcode 10

---

bin/templates/scripts/cordova/lib/copy-www-build-step.js

ios
To fix #407 with automatic provioning.
This PR fixs the issue that `ios-deploy` (`cordova run --device`) can not work with automatic provisoning. 
This PR simply remove following lines 
```
shell.rm('-rf', path.join(dstDir, '_CodeSignature'));
shell.rm('-rf', path.join(dstDir, 'PkgInfo'));
shell.rm('-rf', path.join(dstDir, 'embedded.mobileprovision'));
```
in cordova/lib/copy-www-build-step.js.
I am not sure why that codes are here.
But I image that the old version of the cordova use `xcrun` for the certification after building process. In such situation, the above codes are necessary.
However I found that these codes lead strange behavior with automatic provisioning in ios-deploy (in `cordova run --device`) as reported in #407 .
I test as following on my local mac (mojave).
1. …

GH-407: remove removing certificates functions in xcode post scripts

---

CordovaLib/Classes/Public/CDVPluginResult.h
CordovaLib/Classes/Public/CDVPluginResult.m

This allows Swift plugins to write code like 
``` swift
CDVPluginResult(status: .error)
```
rather than 
``` swift
CDVPluginResult(status: CDVCommandStatus_ERROR)
```
Its use in Objective C is unchanged, but ~this is a **API breaking change** as far as Swift plugins are concerned (so we'd be looking at cordova-ios 6 to land this)~ I've hacked it to support both the existing name and the "friendly" name in Swift, at the cost of the code making sense 😕

Expose CDVCommandStatus enum to Swift

---

package.json

iOS
Resolves https://github.com/apache/cordova-ios/issues/547.
Updates `ios-sim` to version 8.
All unit tests pass. Running the scripts to list emulators presented a list of emulator devices and iOS versions.

Bump ios-sim to v8 to fix simulator listing

---

bin/templates/scripts/cordova/Api.js

cordova-ios
Fixing the issue #523 
To avoid error on windows, adding checks cocoapods is available or not before changing swift version of cocoapods libraries.
In my local Mac,
create project and adding phonegap-plugin-push.
Checking build.
Checking the application can receive push notifications.
(by using cordova@nightly)
In my local Windows 10,
create project and adding phonegap-plugin-push.
Checking to skip the cocoapods specific process.
(by using cordova@8.1.0)

GH-523 : ignore swift version settings of cocoapods libraries on windows

---

CordovaLib/CordovaLib.xcodeproj/project.pbxproj

- `cordova-ios 5.0.0`
- The newly added dynamic target in the `CordovaLib` project does not get embedded correctly in an app binary. Attempting to build an `IPA` file will throw a `dylib not found` error with `Cordova.framework`.
- Details in [this GitHub issue](https://github.com/apache/cordova-ios/issues/559).
- Changes are simple and isolated.
- Added the default base path that's required for a dynamic target.
- Tested extensively with my own project.

GH-559 Fixing dynamic framework installation path

---

README.md

Continuation from PR #386: show minimum Xcode version as 9.x (deprecated) or 10.
This is assuming that the issues with Xcode 10 discussed in #407 are resolved by the time we make the new release of cordova-ios.
~~P.S. Linking to apache/cordova-docs#863: Minimum Xcode version in cordova-docs & cordova-ios not consistent~~ (sorry apache/cordova-docs#863 was an old issue, will raise a new issue to track this one)

[WIP] Update Xcode version supported (9.x/10.x/...)

---

bin/templates/scripts/cordova/lib/prepare.js

IOs
when:
- setting the target device `<preference name="target-device" value="handset" />`
- using (any) plugins
- Adding a resource file `<resource-file src="GoogleService-Info.plist" />`
then:
`TARGETED_DEVICE_FAMILY` is reset to the default value of "1,2" while adding the resource file after handling the target device.
Instead of creating a new instance of the xcode project via `new xcode.project([...])` use the wrapped xcode project via `projectFile.parse([...])`.
This will reuse the cached xcode project, which is created when adding the plugins, and therefore maintain the changes when setting the target device.
The cached xcode project will then also be used when adding the resource file.
- add plugins
- set target-device to handheld
- add a resource file
verify, that …

(ios) Fix setting of target-device to handset in combination with plugins and resource files

---

CordovaLib/Classes/Private/Plugins/CDVUIWebViewEngine/CDVUIWebViewDelegate.m

iOS
Fix issue 447 UIWebView call loadRequest multiple times lead to deadlock in iOS12.
The number of callback of `webViewDidStartLoad`  and `webViewDidFinishLoad`  is not equal.`_loadCount` will never equals 1, delegate's `webViewDidFinishLoad` and `[CDVUserAgentUtil releaseLock:vc.userAgentLockToken];` will never call.Then new CDVViewcontroller  won't load page.

UIWebView call loadRequest multiple times lead to deadlock in iOS12 (fixes #447)

---

bin/templates/scripts/cordova/Api.js

Override id with  ios-CFBundleIdentifier  when both id and ios-CFBundleIdentifier are defined in config.xml
iOS
When both id and ios-CFBundleIdentifier are defined in config.xml, Xcode project should be created with  ios-CFBundleIdentifier as the bundle identifier. Else, bundle identifier should be the id.
https://github.com/apache/cordova-ios/issues/565
Check both packageName(i.e. id) and ios-CFBundleIdentifier when creating the platform (Xcode project)
Tested these scenarios,
1. config.xml with both id and ios-CFBundleIdentifier
2. config.xml with id only
3. config.xml with ios-CFBundleIdentifier only
- [X ] I've run the tests to see all new and existing tests pass
- [ X] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to …

Override id with ios-CFBundleIdentifier

---

bin/templates/scripts/cordova/lib/prepare.js

This is causing a crash if someone whitelists just a protocol, ex `file://`
See #539
iOS
Reviewed the code, and made the change.

Null check for missing pathname #539

---

bin/templates/scripts/cordova/Api.js

ios
See #535: The ConfigParser passed in by cordova-lib is constructed from the cordova-common version that cordova-lib is using, rather than the one that cordova-ios is using.
Initialize the ConfigParser at the platform API level so that it uses the expected version.
All unit tests pass.

Run prepare with the correct ConfigParser version

---

bin/templates/scripts/cordova/lib/Podfile.js

iOS
When plugin framework tag contains an empty spec value (`spec=""`), Podfile becomes malformed and `pod install` command fails with
```
ArgumentError - Illformed requirement `""`
```
Example:
```xml
<framework src="Fabric" type="podspec" spec="~> 1.7.6"/>
<framework src="Crashlytics" type="podspec" spec="~> 3.10.1"/>
<framework src="Firebase/Core" type="podspec" spec=""/>
```
Creates
```
pod 'Fabric', '~> 1.7.6'
pod 'Crashlytics', '~> 3.10.1'
pod 'Firebase/Core', ''
```
Proposed change checks for an empty spec value and doesn't write version number:
```
pod 'Fabric', '~> 1.7.6'
pod 'Crashlytics', '~> 3.10.1'
pod 'Firebase/Core'
```
I'm not sure if it's a bug in cordova-ios or specific plugin ([cordova-plugin-firebase-crashlytics](https://github.com/ReallySmallSoftware/cordova-plugin-fir …

Don't write spec to podfile when it's an empty string

---

package.json

This closes #586
I tested it by installing `ios-sim@8.0.1` locally in a cordova project. Before the update, there are no virtual devices listed. After the update, there are virtual devices listed.

fix: iOS device list is empty

---

bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/run.js
package.json

Currently the simulator selection and app deployment on the selected simulator is a bit of a black box, the logging is insufficient to properly understand and retrace what is happening.
- When building for simulator
- display more information about the simulator being built for (simulator ID, simulator identifier string):  
```
$ cordova run ios --no-telemetry --no-update-notifier --target iPhone-XR --emulator
Building for "iPhone X" Simulator (com.apple.CoreSimulator.SimDeviceType.iPhone-X, iPhone-X)
```
- before executing `xcodebuild` command, output the `emulatorTarget` that will be used as part of `-destination` option:  
```
Building project: /private/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp-2604oc4wBu2VePt9/platforms/ios/HelloCordova.xcworkspace
Configuration: Debug …
```

More logging for simulator selection and deployment

---

package.json

Wanting to get this in before doing the 5.0.1 release.
None? This was a dev dependency only
There was an npm audit warning from a subdependency of nyc
Update nyc
`npm run cover` finished successfully and output coverage info

Update nyc to get rid of npm audit warnings

---

package.json
tests/spec/unit/Api.spec.js
tests/spec/unit/lib/list-devices.spec.js

Fixes #393.
The tests that failed after the jasmine update both did not handle their promises properly. They also were broken beyond that, which seemed to have been nicely covered up by the old version of jasmine.
I could only run the unit tests on Linux. Let's see if anything else is broken...

Update jasmine & fix broken tests

---

bin/templates/scripts/cordova/lib/Podfile.js

We updated the templates and cordovaLib to use 10.0 as deployment target in 5.0, but was not changed here in the Podfile generation.

Bump default minDeploymentTarget to 10.0 in Podfile

---

bin/templates/scripts/cordova/lib/build.js

An error message is missing a space in the error message, and the log is missing the path completely because it doesn't concat the string
closes #648
Fix both issues.
none

fix(build.json): spacing in error message and missing path in log

---

package.json

Runs `xcodebuild` w/ `-quiet` flag during testing. With this flag, `xcodebuild` will only show warnings and errors. This reduces the Travis CI log from over 4k lines to just over 2k lines.

Reduce verbosity of xcodebuild output during tests

---

tests/spec/component/versions.spec.js
tests/spec/unit/Api.spec.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/build.spec.js
tests/spec/unit/lib/run.spec.js
tests/spec/unit/prepare.spec.js
tests/spec/unit/preparePlatform.spec.js
tests/spec/unit/versions.spec.js

Let Jasmine handle async test results

---

package.json

Moves all common `xcodebuild` arguments used in npm scripts to a new script called `xcodebuild`.

Reuse common xcodebuild arguments in npm scripts

---

bin/templates/scripts/cordova/lib/prepare.js

This is extremely confusing if your editor is not configured to clearly distinguish different sorts of whitespce
iOS
This is just clean code style IMHO

Don't use whitespace as an indent indicator

---

.travis.yml

Lately the ObjC tests that were using Xcode 10.1 on CI have been very unstable. It was not uncommon that two out of four CI runs failed. [The Error](https://travis-ci.org/apache/cordova-ios/jobs/604550483#L2258-L2260) is always the same and seems to be caused by a [known defect](https://github.com/microsoft/azure-pipelines-tasks/issues/8840) in Xcode 10.1. The only known fix seems to be not to use 10.1. So that's what we will do.
I've updated our Travis CI config to use Xcode 9.4 and 10.3 respectively. The update of Xcode 9 is not necessary, but since it's the current default for Travis CI ObjC images I thought it wouldn't hurt.
I've let the five CI jobs run four times each on my fork's CI with these changes and there were no errors.

Update Xcode versions used in CI to latest minor release

---

bin/templates/scripts/cordova/lib/check_reqs.js
tests/spec/unit/lib/check_reqs.spec.js

Starting on 1.8.0, cocoapods now use CDN to avoid having to sync the master repo, so we don't need to check anymore if the repo is populated.
Even more, the "pod setup" command now doesn't do anything, and newer versions of cocoapods are actually incompatible with cordova-ios, as the repository filled check will kick in and make it impossible to use it.
Error example with meteor and cocoapods 1.8.4:
✗ CocoaPods: The CocoaPods repo has not been synced yet, this will take a long
time (approximately 500MB as of Sept 2016). Please run `pod setup` first to
sync the repo.
This also solves issue #700

Add check for newer versions of cocoapods to avoid locking adding platforms on non synced pods repo

---

bin/lib/create.js

prepare is being run before add command finish because `fs.lstat` is async and the `createProject` is resolving before `fs.lstat` finishes.
This PR changes `fs.lstat` to `fs.lstatSync` to make the directory check sync and avoid to resolve before all create work is done.
Closes #725

fix: make prepare wait for add to finish

---

.travis.yml
appveyor.yml
package.json

* Follow inline with Node Support
* Prepare for next major
* https://github.com/apache/cordova/issues/79
* Bump `engines.node` to `>=10` in `package.json`
* Drop node 6 and 8 from CI services.
- `npm t`
- CI services continue to pass

chore: bump node requirement (>=10)

---

.eslintrc.yml
.travis.yml
appveyor.yml
bin/create
bin/lib/create.js
bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/build
bin/templates/scripts/cordova/clean
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/check_reqs.js
bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js
bin/templates/scripts/cordova/lib/prepare.js
bin/templates/scripts/cordova/lib/run.js
bin/templates/scripts/cordova/run
bin/update
cordova-js-src/.eslintrc.yml
cordova-js-src/exec.js
cordova-js-src/plugin/ios/logger.js
package.json
tests/spec/.eslintrc.yml
tests/spec/create.spec.js
tests/spec/unit/Api.spec.js
tests/spec/unit/BridgingHeader.spec.js
tests/spec/unit/Plugman/common.spec.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/Podfile.spec.js
tests/spec/unit/PodsJson.spec.js
tests/spec/unit/build.spec.js
tests/spec/unit/prepare.spec.js
tests/spec/unit/preparePlatform.spec.js

Code syntax cleanup
* replace dependencies with @cordova/eslint-config
* update eslint config
* eslint automatic and manual corrections
This PR require #743 to be merged first.
- `npm t`
- `npm run lint`

chore: updated eslint with applied fix

---

bin/templates/scripts/cordova/Api.js

replaces #752 
closes #721
replaces variables with the variable value
plugin for testing with variables in both podspec and framework
https://github.com/jcesarmobile/cordova-plugin-firebase-dynamiclinks

fix: replace variables in Podfile

---

bin/lib/create.js
bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/BridgingHeader.js
bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/check_reqs.js
bin/templates/scripts/cordova/lib/clean.js
bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js
bin/templates/scripts/cordova/lib/prepare.js
bin/templates/scripts/cordova/lib/projectFile.js
bin/templates/scripts/cordova/lib/run.js
bin/templates/scripts/cordova/lib/spawn.js
bin/templates/scripts/cordova/lib/versions.js
tests/spec/component/versions.spec.js
tests/spec/create.spec.js
tests/spec/unit/Api.spec.js
tests/spec/unit/BridgingHeader.spec.js
tests/spec/unit/Plugman/common.spec.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/Podfile.spec.js
tests/spec/unit/PodsJson.spec.js
tests/spec/unit/build.spec.js
tests/spec/unit/lib/check_reqs.spec.js
tests/spec/unit/lib/list-devices.spec.js
tests/spec/unit/lib/list-emulator-images.spec.js
tests/spec/unit/lib/run.spec.js
tests/spec/unit/prepare.spec.js
tests/spec/unit/preparePlatform.spec.js
tests/spec/unit/projectFile.spec.js
tests/spec/unit/versions.spec.js

Modernize code
* Use `lebab` to apply `--transform arrow` and `--transform arrow-return`.
* Reverted some of the applied `arrow-return` for readability.
- `npm t`

refactor: use arrow functions

---

bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/prepare.js

Creating an alias is not required if using `arrow` functions.
* Searched and removed `self = this` and anything that used `self.`
- `npm t`

refactor: do not alias this to self

---

bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/BridgingHeader.js
bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/check_reqs.js
bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js
bin/templates/scripts/cordova/lib/prepare.js
bin/templates/scripts/cordova/lib/projectFile.js
tests/spec/unit/BridgingHeader.spec.js
tests/spec/unit/prepare.spec.js

Modernize code
Use `lebab` to apply `--transform obj-shorthand`.
- `npm t`

refactor: transform object shorthand

---

tests/spec/unit/Api.spec.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/prepare.spec.js

This maybe a personal opinion but, I feel that split out the variables can make it:
* easier to search for the variable declaration.
* quicker to distinguish the change/add/remove of a variable in a diff when on its own line.
* Use `lebab` to apply `--transform multi-var `.
- `npm t`

refactor: transform split out variables

---

bin/lib/create.js
bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/BridgingHeader.js
bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/check_reqs.js
bin/templates/scripts/cordova/lib/clean.js
bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js
bin/templates/scripts/cordova/lib/prepare.js
bin/templates/scripts/cordova/lib/run.js
bin/templates/scripts/cordova/lib/spawn.js
bin/templates/scripts/cordova/lib/versions.js
tests/scripts/killsim.js
tests/spec/unit/Api.spec.js
tests/spec/unit/BridgingHeader.spec.js
tests/spec/unit/Plugman/common.spec.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/Podfile.spec.js
tests/spec/unit/build.spec.js
tests/spec/unit/prepare.spec.js
tests/spec/unit/preparePlatform.spec.js

Modernize code
Use `lebab` to apply `--transform template`.
- `npm t`

refactor: use template strings

---

bin/lib/create.js
bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/list-devices
bin/templates/scripts/cordova/lib/list-emulator-images
bin/templates/scripts/cordova/lib/list-started-emulators
bin/templates/scripts/cordova/lib/listDevices.js
bin/templates/scripts/cordova/lib/listEmulatorBuildTargets.js
bin/templates/scripts/cordova/lib/listEmulatorImages.js
bin/templates/scripts/cordova/lib/listStartedEmulators.js
bin/templates/scripts/cordova/lib/run.js
bin/templates/scripts/cordova/lib/versions.js
bin/templates/scripts/cordova/version
tests/spec/unit/lib/list-devices.spec.js
tests/spec/unit/lib/list-emulator-images.spec.js

Fix failing tests.
Bin files that contains the shebang interpreter fails when being required.
Example Error:
> /Users/travis/build/apache/cordova-ios/bin/templates/scripts/cordova/lib/list-devices:1
(function (exports, require, module, __filename, __dirname) { #!/usr/bin/env node
^
> SyntaxError: Invalid or unexpected token
https://travis-ci.org/apache/cordova-ios/jobs/649198385#L1474
* Keep the bin files with the shebang interpreter but pull out all the code into a separate JS file. The bin files require the newly created JS files and execute them as usual.
* Update everywhere else that use to require the bin but now require the newly created JS files which do not contain the shebang interpreter.
**Additional Notes:**
The version bin file, which contains the platform version, is updated …

fix (node): require failure with shebang interpreter

---

bin/templates/project/__PROJECT_NAME__/config.xml
bin/templates/scripts/cordova/defaults.xml

Fix error when calling WebViewEngine JavaScript Code.
When calling the WebViewEngine JavaScript
```
window.WkWebView.allowsBackForwardNavigationGestures(true);
```
The code does not process and an error displays in the Native logs,
> 2020-02-13 18:51:12.416046+0900 MyAppName[48951:8545412] ERROR: Plugin 'CDVWebViewEngine' not found, or is not a CDVPlugin. Check your plugin mapping in config.xml.
2020-02-13 18:51:12.416177+0900 MyAppName[48951:8545412] FAILED pluginJSON = ["INVALID","CDVWebViewEngine","allowsBackForwardNavigationGestures",[true]]
This PR adds the missing declaration which makes the JavaScript work again. 
- `npm t`
- `cordova build ios`
- Run Simulator
- Test JavaScript method and verify execution

fix (CDVWebViewEngine): JavaScript to Native Call Not Working

---

bin/templates/project/__PROJECT_NAME__/Classes/MainViewController.m
tests/CordovaLibTests/CordovaLibApp/ViewController.m
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Classes/MainViewController.m

Remove deprecated code.
https://developer.apple.com/documentation/uikit/uiviewcontroller/1621383-viewdidunload
Deleted `viewDidUnload` usage.
- `npm t`

chore: remove deprecated method viewDidUnload

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

Replace deprecated `stringByAddingPercentEscapesUsingEncoding` method with `stringByAddingPercentEncodingWithAllowedCharacters`
https://developer.apple.com/documentation/foundation/nsstring/1415058-stringbyaddingpercentescapesusin
- `npm t`

fix: replace deprecated stringByAddingPercentEscapesUsingEncoding usage

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
bin/templates/project/__PROJECT_NAME__/config.xml
bin/templates/scripts/cordova/defaults.xml
bin/templates/scripts/cordova/lib/prepare.js
tests/CordovaLibTests/CDVWebViewEngineTest.m
tests/CordovaLibTests/CordovaLibApp/config.xml
tests/spec/unit/fixtures/ios-config-xml/SampleApp/config.xml

Apple has deprecated the `mediaPlaybackRequiresUserAction` property in iOS 8.0–9.0.
This property should be replaced with `mediaTypesRequiringUserActionForPlayback`.
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1614727-mediaplaybackrequiresuseraction
This PR:
* Updates the native side to use the new property name.
* Updates to read the new preference name (`MediaTypesRequiringUserActionForPlayback`) from `config.xml`
* Warn users that the preference is being deprecated in the near future if it is still being used.
* Fallback on the the value from the old preference name if it still remains.
- `npm t`
- `cordova build ios`

refactor: deprecate mediaPlaybackRequiresUserAction

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
bin/templates/scripts/cordova/lib/prepare.js
tests/CordovaLibTests/CDVWebViewEngineTest.m

Apple has deprecated the `mediaPlaybackAllowsAirPlay` property in iOS iOS 8.0-9.0.
This property should be replaced with `allowsAirPlayForMediaPlayback`.
https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1614726-mediaplaybackallowsairplay
This PR:
* Updates the native side to use the new property name.
* Updates to read the new preference name (`AllowsAirPlayForMediaPlayback`) from `config.xml`
* Warn users that the preference is being deprecated in the near future if it is still being used.
* Fallback on the the value from the old preference name if it still remains.
- `npm t`
- `cordova build ios`

refactor: deprecate mediaPlaybackAllowsAirPlay

---

CordovaLib/Classes/Public/NSDictionary+CordovaPreferences.m

Improve the boolean checks for preference settings and logging.
Updated the `cordovaBoolSettingForKey` method.
- `npm t`
- `cordova build`
- Run in simulator and test with different values

refactor (cordovaBoolSettingForKey): improve boolean checks and native logging

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
bin/templates/scripts/cordova/defaults.xml
bin/templates/scripts/cordova/lib/prepare.js
tests/CordovaLibTests/CDVWebViewEngineTest.m

`MediaPlaybackRequiresUserAction` was replaced with `MediaTypesRequiringUserActionForPlayback` in a previous PR. Since the `MediaTypesRequiringUserActionForPlayback` defaults will always exist in `defaults.xml`, `MediaPlaybackRequiresUserAction` will never be read. The old preference logic should actually be removed.
Additionally, the old preference `MediaPlaybackRequiresUserAction`  accepted `boolean` values but the new `MediaTypesRequiringUserActionForPlayback` preference does not accept boolean. This needs to be corrected to accept proper value types.
This PR removes all of `MediaPlaybackRequiresUserAction` logic except for the deprecated warning. The warning is used to provide users a migration step. It will be removed in a later release.
This PR has also updated the native code to …

breaking: remove MediaPlaybackRequiresUserAction and update MediaTypesRequiringUserActionForPlayback to proper variable types

---

tests/CordovaLibTests/CDVWebViewEngineTest.m

Comment says default value is "NO", but that was for the old entry, the new entry doesn't allow "NO".
I've put "none" since that's the default in defaults.xml

tests: change comment values for MediaTypesRequiringUserActionForPlayback

---

CordovaLib/CordovaLib.xcodeproj/xcshareddata/xcschemes/Cordova.xcscheme
tests/CordovaLibTests/CordovaLibApp/CordovaLibApp-Info.plist
tests/CordovaLibTests/CordovaLibTests-Info.plist
tests/CordovaLibTests/CordovaLibTests.xcodeproj/project.pbxproj
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaFrameworkApp.xcscheme
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaLib.xcscheme
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaLibApp.xcscheme
tests/cordova-ios.xcworkspace/xcshareddata/xcschemes/CordovaLibTests.xcscheme

Continue to remove warnings and bringing the repo up-to-date
* Perform Xcode recommended update
* Migrate localization
* Enable Base Internationalization
Changes are primarily directed to `CordovaLibTests` but as the project is loaded though `cordova-ios.xcworkspace`, Xcode also cleaned up one area in `CordovaLib`. Those changes are  safe to be applied with this PR.
- `npm t`

refactor: applied various xcode recommended update

---

bin/templates/project/__TEMP__.xcodeproj/project.pbxproj
tests/spec/unit/fixtures/ios-config-xml/SampleApp.xcodeproj/project.pbxproj

Apply Xcode Recommendation to enable the static analyzer to check for missing localizability.
Added `CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED` flag.
This flag will only warn when a non-localized string is passed to a user-interface method. It will help people understand why something might not display in the correct localization.
- `npm t`

feature: add CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED

---

README.md

The wiki is moved to Confluence, and there is no Cordova content there. I've also checked the Cordova main site and there are no links to a wiki from there.

Remove dead link to wiki from README

---

CordovaLib/Classes/Public/CDVAppDelegate.m
CordovaLib/Classes/Public/CDVScreenOrientationDelegate.h
CordovaLib/Classes/Public/CDVViewController.m
bin/templates/project/__PROJECT_NAME__/Classes/MainViewController.m
tests/CordovaLibTests/CordovaLibApp/ViewController.m
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Classes/MainViewController.m

`- (NSUInteger)application:(UIApplication*)application supportedInterfaceOrientationsForWindow:(UIWindow*)window`, `- (NSUInteger)supportedInterfaceOrientations;` and  `- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation` were deprecated on iOS 6, remove the code as is not being used.
I think it's not breaking since we have the new methods that replaced them.
closes https://github.com/apache/cordova-ios/issues/821

chore: remove deprecated orientation methods

---

bin/templates/scripts/cordova/lib/prepare.js

iOS
Closes #538
Apps with multiple targets get their bundleids in those targets not overwritten anymore
Requires two changes in the xcode package https://github.com/apache/cordova-node-xcode/pull/106 and
https://github.com/apache/cordova-node-xcode/pull/79
**RELEASED in xcode package 3.0.0**
Can be tested with an app with multiple targets with this branch https://github.com/GEDYSIntraWare/cordova-ios/tree/targetfixed

Only set bundleid to main app target

---

bin/templates/project/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist

iOS
The orientation is already set on each build, taking into account possible `preference` directives for the `Orientation`. Pre-setting them here, makes it impossible to reduce the array of available orientations, because `config-file` can not reduce the elements in an array.

Don't pre-fill orientation

---

CordovaLib/Classes/Public/CDVPluginResult.m
CordovaLib/Classes/Public/CDVViewController.m

iOS
I hate disregarded warnings at compile time.
Existing code was converting to NSNumber with wrong init method for the type. 
Rather than change the method called I switched to auto boxing the values which automatically does the right thing in less code.
Ran npm test

(iOS) Fix two compile-time type warnings and simplify code by using auto boxing of NSNumber.

---

package.json

Bump `cordova-common` dependency to latest version.
* cordova-common@^4.0.1
*NOTE: currently using a patch release git tag and will migrate to official released package before merging*
- `npm t`

breaking: bump cordova-common@4.0.1

---

bin/templates/scripts/cordova/lib/check_reqs.js
tests/spec/unit/lib/check_reqs.spec.js

Improve `cocoapods` support by increasing the minimum required version and removing unused logic.
* Increase minimum supported version starting at 1.8.0
* Since 1.8.0, CDN is enabled by default and is highly recommended as it no longer requires to checkout and sync the cocoapods repo. This greatly improves the speed.
- `npm t`

breaking(pod): remove unused API & bump minimum version requirements to 1.8.0

---

bin/lib/create.js
bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/BridgingHeader.js
bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/PodsJson.js
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/plugman/pluginHandlers.js
bin/templates/scripts/cordova/lib/prepare.js
bin/templates/scripts/cordova/lib/projectFile.js
package.json
tests/spec/unit/Api.spec.js
tests/spec/unit/BridgingHeader.spec.js
tests/spec/unit/Plugman/common.spec.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/Podfile.spec.js
tests/spec/unit/PodsJson.spec.js
tests/spec/unit/fixtures/prepare/allows-arbitrary-loads-for-media-false.xml
tests/spec/unit/fixtures/prepare/allows-arbitrary-loads-for-media-true.xml
tests/spec/unit/fixtures/prepare/allows-arbitrary-loads-in-media-false.xml
tests/spec/unit/fixtures/prepare/allows-arbitrary-loads-in-media-true.xml
tests/spec/unit/fixtures/prepare/allows-arbitrary-loads-in-web-content-true.xml
tests/spec/unit/fixtures/prepare/allows-local-networking-true.xml
tests/spec/unit/fixtures/prepare/set-origin-with-mixed-nsallows.xml
tests/spec/unit/fixtures/prepare/wildcard-navigation-with-mixed-nsallows.xml
tests/spec/unit/fixtures/prepare/wildcard-navigation.xml
tests/spec/unit/fixtures/prepare/wildcard-with-mixed-nsallows.xml
tests/spec/unit/prepare.spec.js
tests/spec/unit/preparePlatform.spec.js

* Add `fs-extra` dependency
* Replace `fs` usage with `fs-extra`
* Replace test spec xml generating logic and use pre-made xml test fixtures. Lower the amount of call mocks with actual tool usage for improved testing. 
- `npm t`

breaking: add & use fs-extra w/ fixes

---

bin/cordova_plist_to_config_xml

These changes should be compatible with both Python 2 and Python 3.

Add Python 3 compatibility to bin/cordova_plist_to_config_xml

---

.npmignore

- Add `.npmignore` file
- Remove files that are not needed to be packaged with the release build.
- Decrease package size
```
=== Tarball Details ===
package size:  1.9 MB
unpacked size: 3.5 MB
total files:   390
```
```
=== Tarball Details ===
package size:  420.0 kB
unpacked size: 1.2 MB
total files:   185
```
- `cordova build`
- `cordova run`

chore (npm): add ignore list

---

package-lock.json
package.json

- `ios-sim` 9.x is not ready to be used per advisory: https://github.com/apache/cordova-ios/issues/567
- `ios-sim` 9.x has an error with logging method calls due to scoping issue.
```
'          this.log(`logPath: ${path.resolve(flags.log)}`)\n' +
'               ^\n' +
'\n' +
"TypeError: Cannot read property 'log' of undefined\n" +
```
- revert to the latest on 8.x release (`^8.0.2`)
- `npm t`

revert: ios-sim ^9.0.0 to ^8.0.2

---

bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/prepare.js
package-lock.json
package.json
tests/spec/unit/Api.spec.js
tests/spec/unit/prepare.spec.js

- Use our latest version of ESlint config dev dependency.
- Apply lint corrections
- Include a rebuilt `package-lock.json`
- `npm t`

refactor: bump eslint w/ lint fix & rebuilt package-lock

---

CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVIntentAndNavigationFilter.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/cordova.js
cordova-js-src/plugin/ios/wkwebkit.js

Use `file` as default scheme to avoid break in current apps/
1. defaults to `file` if preference `scheme` is not set.
2. continue to uses `file` if preference scheme is set to `file`.
3. use what ever value the user defines in as preference `scheme` as a custom scheme handler, excluding `file` which was defined in the above case 2.
4. preference `hostname` is only used when `scheme` is not `file`.
5. `CDV_ASSETS_URL` is set to `<scheme>://<hostname>` 
-> if `file`, `hostname = “”`.
-> if `!file`, `hostname = "localhost"` or user define value for preference `hostname`.
6. Extension of above case 3, if `scheme` is set and is not `file`, it will also validate against `WKWebView handlesURLScheme`, if it is not valid, it will default to `app`
- cordova build
- run in simulator

refactor: default to file scheme

---

CordovaLib/CordovaLib.xcodeproj/project.pbxproj

This changes are done by Xcode if selecting enable base internalization
Not sure why CDVViewController+LaunchScreen.h/m get removed, but I can't find the files, so looks like they were removed prior to this change?

chore: enable base internalization for CordovaLib

---

README.md
package-lock.json
package.json

* Final cleanup to various areas:
* Improved the `README.md` syntax format, links, and requirements
* Updated the `package.json` repo and bug to short notation format
* Rebuilt the `package-lock.json`
- `npm t`

chore: cleanup & prep for 6.0.0 release

---

bin/create

* Remove leftover q
* Causes an issue when creating project with create binary.
```
TypeError: Api.createPlatform(...).done is not a function
```
- create project with binary.
```bash
./bin/create /tmp/cdvTest com.foobar.cdvTest cdvTest
Creating Cordova project for the iOS platform:
Path: ../../../../../../../../tmp/cordova-coho-tests/iosTest2
Package: com.foobar.cdvTest
Name: cdvTest
iOS project created with cordova-ios@6.0.0-dev
```

fix: remove q leftover

---

Cordova.podspec

the variable is called `packageJson`, but read the version from `package['version']`, that fails as it doesn't exist.

fix: Properly get version from package.json

---

Cordova.podspec

author and tag are wrong
to use the variable it needs a #
the author should not be between { } unless it uses a name => mail format

chore: fix other podspec errors

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

iOS
This adds a prefrence to the webview which is useful for iPads. Apple introduced a setting which by defaults changes the useragent of iPads from `iPad` to `Macintosh` to provide a "desktop browsing experience". The new preference allows to change the default value.
See original issue from IAB: apache/cordova-plugin-inappbrowser#687
Changed like : apache/cordova-plugin-inappbrowser#688
Documenation: https://github.com/apache/cordova-docs/pull/1083
Automatic tests still pass. I found no automatic tests for preferences at build time.
I created a blank new app, added this platform and checked `navigator.userAgent` while changing the preference. It should be `iPad` for `mobile` and `Macintosh` for `desktop`.

Add PreferredContentMode preference

---

bin/templates/scripts/cordova/lib/prepare.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-json/empty.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-json/single-2xanyany.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-json/varied-device-and-theme.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-json/varied-device.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-map/empty-map.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-map/typical-universal-map.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-map/varied-device-and-theme-map.js
tests/spec/unit/fixtures/launch-storyboard-support/contents-map/varied-device-map.js
tests/spec/unit/prepare.spec.js

This is my first pr so please don't burn me at the stake. 
iOS
I wanted to include a dark mode variant of my app's splash screen, but found that Cordova did not yet support this feature. It turns out that it only took a few lines of code, so I figured I'd share it here.
I found this related issue: https://github.com/apache/cordova-plugin-splashscreen/issues/246. It turns out that no changes to the splashscreen plugin are necessary to make it happen.
This enables dark mode storyboard images by allowing you to specify splash images based on appearance (dark or light). It checks for ~dark or ~light suffixes in splash images. If neither is found, they're used as the default. It then adds the variants to Contents.json, and the rest is handled by iOS. Example config.xml:
`<splash …

(iOS) Dark mode splashscreen storyboard images

---

bin/templates/project/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist

Reverts apache/cordova-ios#615
These defaults actually match the default values from a standard blank iOS app generated by Xcode, and the lack of these defaults are causing unexpected behaviour (#899).
To restrict the orientation, use the `Orientation` preference in config.xml.

Revert "Don't pre-fill orientation"

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewUIDelegate.h
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewUIDelegate.m

iOS
Currently, attempts to create new windows (via links with `target="_blank"` or JS `window.open`) for pages within the application have no effect and are silently ignored. (Links to pages outside the application trigger the allow-intent functionality and open in Safari.)
With this PR, the default behaviour will be to open those links in the **same** Web View (without creating a new window).
This also introduces a preference (`AllowNewWindows`) that allows the creation of a new UIViewController to present the new page in a new Web View frame on top of the existing Web View.
**Note:** This new window provides no controls, so it can only be closed with `window.close()` in JS.
Manual testing in a new Cordova app.

Don't silently ignore creation of new windows

---

bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/projectFile.js
tests/spec/unit/fixtures/ios-config-xml/SampleApp/SampleApp-Info.plist
tests/spec/unit/fixtures/org.test.plugins.dummyplugin/plugin.xml
tests/spec/unit/pluginAdd.spec.js

iOS
When installing plugins, the `$PACKAGE_NAME` value was pulled from the Info.plist, which is the string `$(PRODUCT_BUNDLE_IDENTIFIER)` instead of the actual value of the PRODUCT_BUNDLE_IDENTIFIER as defined in the Xcode project file.
Change `getPackageName()` to always try to replace `$(...)` variables with their values from the Xcode Project.
Added spec tests, and manual testing.

Set $PROJECT_NAME properly when installing plugins

---

bin/templates/scripts/cordova/lib/run.js

cordova-ios used to use "mv -f" and it was replaced with fs-extra.moveSync.  moveSync behaves
differently than mv, which broke deployment to devices.  This fixes the folder move and
subsequently deployment to device (when using "cordova run ios --device ..."
This was motivated by wanting to run an ios app on the device.  This worked in versions of cordova-ios <= 5.1.1 and was broken in 6.0.0 and 6.1.0.
fixes: https://github.com/apache/cordova-ios/issues/912
Fix a file copy.  The behavior of `moveSync` is not exactly the same as `mv -f` which was previously used.
I have tested by deploying ios apps with `cordova run ios --device` from the command line.  This restores the functionality from the old versions of cordova-ios.

(ios) issue-912: fix deployment to device

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

When using a custom scheme (app in example), the initial url loaded is `app://localhost`
This PR makes the initial url loaded to append the startURL to the url, in example `app://localhost/index.html`
This makes possible to run the tests as they use `<content src="cdvtests/index.html" />`, so now the url loaded will be `app://localhost/cdvtests/index.html` instead of `app://localhost`.

fix: Append startURL to the initial url loaded

---

package-lock.json
package.json

iOS
Routine dependency updates
Update npm dependencies.
Fixes some audit warnings about lodash, and also ensure we are using
cordova-common 4.0.2 with the fix for Info.plist files.
Waiting for CI to build and run this.

chore: Update npm dependencies

---

.asf.yaml

* Corrects the repo topics to more accurately reflect the languages actually in use (no more "cplusplus" or "csharp" topics)
* Adds the [Hacktoberfest opt-in topic](https://hacktoberfest.digitalocean.com/hacktoberfest-update)
* Turns off GitHub Projects for the repo (we use them at the org instead)
* Aligns with our goal of using squash commits when merging pull requests by disabling the merge and rebase options

chore(asf): Update GitHub repo metadata

---

bin/templates/scripts/cordova/lib/prepare.js
tests/spec/unit/prepare.spec.js

iOS
The guy who implemented this background colour parsing code forgot that lowercase letters existed when writing the regex 🙄
([aka, me](https://github.com/apache/cordova-ios/pull/896))
Adds support for lowercase hex characters in `BackgroundColor` preference parsing, along with appropriate tests.
Added additional test cases with lowercase characters.

Fix BackgroundColor parsing for lowercase letters

---

CordovaLib/Classes/Public/CDVViewController.m

Fixes #991
iOS
The `cordova-plugin-splash-screen` allowed to hide the splash screen as a race between the timeout specified in the `SplashScreenDelay` preference and the call to `navigator.splashscreen.hide()` in JS code. This was very desirable, it allowed to show the splash screen for a long time if the application took a long time to boot but not too long so that users wouldn't think that the application is hanging.
Since the reimplementation of this functionality here, the behavior has changed. Now, the `SplashScreenDelay` preference applies to calls made by `navigator.splashscreen.hide()`, defeating the behavior described above.
Make hiding of splash screen again a race between the timeout specified in `SplashScreenDelay` setting and `navigator.splashscreen.hide()` call.
Manual tests …

Hide splash sceen without `SplashScreenDelay` on .hide()

---

CordovaLib/CordovaLib.xcodeproj/project.pbxproj

iOS
If your application consumes cordova as a submodule and depends on the cordova dynamic framework, it will fail to run properly because the web view engine classes are not in the framework.
As a result, CDVViewController fails to build the web view engine by reflection.
```obj-c
self.webViewEngine = [[NSClassFromString(defaultWebViewEngineClass) alloc] initWithFrame:bounds];
```
And the view controller is never unhidden.
The change simply adds the cordova framework as a target for the web view engine classes.
In https://github.com/forcedotcom/salesforceMobileSDK-ios-hybrid, we consume cordova through a submodule.
We have several sample apps as well as suites of tests. The change allowed the apps to run properly and the tests to pass.

(iOS) Project changes to allow consuming cordova as submodule

---

bin/templates/scripts/cordova/lib/check_reqs.js

- host environment
- iOS xcode project generation
Ignore CocoaPods check and installation on non-darwin (macOS) platforms.
Manual tests:
- cordova plugin add cordova-plugin-firebase-crashlytics
- cordova plugin rm cordova-plugin-firebase-crashlytics
Tested on docker-linux: "Debian GNU/Linux 9 (stretch)"
Tested on Mac OS X:
- ProductVersion: 10.15.7
- BuildVersion: 19H2
cordova-ios: npm test - the results are below
On Linux: try to add a plugin with Cocoapods dependency, e.g.:
- cordova plugin add cordova-plugin-firebase-crashlytics
Cordova throws an error instead of skipping the pod version check.
With this patch, Cordova ignores checking and installing CocoaPods on non-darwin (macOS) platforms.

(iOS) Skip Cocoapods checkTool on non-darwin platform

---

CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVIntentAndNavigationFilter.m

Cordova iOS
The PR that dropped UIWebView in favour of WKWebView (https://github.com/apache/cordova-ios/pull/773) introduced a bug that makes it so that iframe loads potentially jump out of the app and to Safari.
The current behavior is a problem for instance with Google Tag Manager. GTM might insert an iframe on the page with a source of `https://adservice.google.com`, or indeed any other country Google domain, depending on where the user is. This request would be sent out from the app and to Safari with the current implementation. Since the country domain might vary, it is impossible to approve this navigation in the `<allow-navigation />` list in order to keep it within the app.
This PR reinstates a verification that if the navigation type is `other` (for instance an iframe) we verify …

(iOS) Reinstate verification of main navigation in case of navigationType other

---

CordovaLib/Classes/Public/CDVURLSchemeHandler.m

iOS
Data can be `nil` in the WKURLSchemeHandler and should not be passed as a response.
Add simple nil check
Closes #903

(ios): nil check in didReceiveData in schemehandler

---

bin/templates/project/__TEMP__.xcodeproj/project.pbxproj

iOS
Closes GH-1059
In Xcode 12, if an app is linked against .framework files with multiple architectures, it will generate an error about embedded framework mismatches. Declaring this property (even with its default value of `NO`) resolves the issue.
CI passing

GH-1059: Add VALIDATE_WORKSPACE setting to XcodeProj

---

bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/listEmulatorBuildTargets.js

iOS
Closes #594 
Just add two more log messages for how simulators are chosen.
Manual

(ios): add console output for simulator selection

---

CordovaLib/Classes/Public/CDVURLSchemeHandler.h
CordovaLib/Classes/Public/CDVURLSchemeHandler.m

iOS
This offers plugin authors the possibility to plug into the WKURLSchemeHandler. Some options where discussed on the [list](https://lists.apache.org/thread.html/r2df0ee4db5746960d41935833a7bd50fa750ad7c30161b76eb5bf862%40%3Cdev.cordova.apache.org%3E)
I did this "hook" to implement a plugin which acts as a proxy to bypass CORS and cookie issues: https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy.
Supersedes #1004 
The implementation was based on the discussions on the list and similarly implemented like `shouldOverrideLoadWithRequest`. Thanks to @erisu for the hint in the right direction.
**TODO**
* install ios platform from this PR
* install plugin https://github.com/GEDYSIntraWare/cordova-plugin-webview-proxy
* convert http/https URL to proxy URL with …

Allow plugins to hook into the WKURLSchemeHandler

---

CordovaLib/Classes/Public/CDVViewController.h
CordovaLib/Classes/Public/CDVViewController.m
bin/templates/project/__PROJECT_NAME__/Classes/MainViewController.m

iOS
Closes #929 
When using CDVViewController via CordovaLib as a library, the app might already be loaded and not need to show the launch storyboard again.
Rather than unconditionally showing the splashscreen until the webview content has loaded, make it initially invisible. Then in the project template, make it visible so that it continues working as expected for apps using the Cordova CLI.
Manual testing

Don't show splashscreen when using standalone CDVViewController

---

bin/templates/scripts/cordova/Api.js

Fail to install plugins with missing podspec config elements.
fixes #913 
Add conditional checks.
* `npm t`
* `plugin add` without `podspec`'s `config` element.
* `plugin add` with `podspec`'s `config` element.

fix: plugin podspec with no config elements

---

package-lock.json
package.json

iOS
Working through the release process I found some outdated dependencies:
```
Package       Current  Wanted  Latest  Location
find-process    1.4.3   1.4.4   1.4.4  cordova-ios
fs-extra        9.0.1   9.1.0   9.1.0  cordova-ios
ios-sim         8.0.2   8.0.2   9.0.0  cordova-ios
jasmine         3.5.0   3.5.0   3.6.4  cordova-ios
nopt            4.0.3   4.0.3   5.0.0  cordova-ios
semver          7.3.2   7.3.4   7.3.4  cordova-ios
tmp             0.1.0   0.1.0   0.2.1  cordova-ios
```
I updated dependencies and found no issues locking at the release notes and test results. They should fit in this minor release.
Some packages turned tests red and are major upgrades. I created an issue for the next version: https://github.com/apache/cordova-ios/issues/1068
Tests and CI

(chore): update dependencies for minor release

---

package-lock.json
package.json

iOS
`cordova-ios` depends on `underscore` but doesn't declare it as a dependency
https://github.com/apache/cordova-ios/blob/048c1cace886d950860236adb893a860dfbd3503/bin/templates/scripts/cordova/lib/projectFile.js#L22
Added `underscore` as a dependency
Ran `cordova prepare ios` under a strict dependency environment

(iOS) add undeclared dependency `underscore`

---

bin/templates/scripts/cordova/Api.js

ios
fixes https://github.com/apache/cordova-ios/issues/1139
replaced the delimiter string with the environment delimiter
I've tested this code on install cordova plugin like `scandit-cordova-datacapture-core`

fix(ios): split xcode project location by env separator

---

bin/templates/project/__PROJECT_NAME__/config.xml
bin/templates/project/www/index.html
bin/templates/scripts/cordova/defaults.xml
tests/CordovaLibTests/CordovaLibApp/config.xml
tests/spec/unit/fixtures/ios-config-xml/SampleApp/config.xml
tests/spec/unit/fixtures/ios-config-xml/cordova/defaults.xml

Cleanup repo to remove more things that are UIWebView related.
* Remove Preference:
* [`GapBetweenPages`](https://developer.apple.com/documentation/uikit/uiwebview/1617943-gapbetweenpages)
* [`KeyboardDisplayRequiresUserAction`](https://developer.apple.com/documentation/uikit/uiwebview/1617967-keyboarddisplayrequiresuseractio)
* [`PageLength`](https://developer.apple.com/documentation/uikit/uiwebview/1617980-pagelength)
* [`PaginationBreakingMode`](https://developer.apple.com/documentation/uikit/uiwebview/1617933-paginationbreakingmode)
* [`PaginationMode`](https://developer.apple.com/documentation/uikit/uiwebview/1617985-paginationmode)
* Removed `gap:` from template.
- N/A

chore: remove more deprecated UIWebView things

---

README.md

iOS
Reviewing Readme between cordova-ios and cordova-android.
Fix typo and add "Debugging in Xcode".
(also see similar PR for cordova-android apache/cordova-android#1308)
.

doc: readme improvements (cleaup, xcode debugging, etc)

---

bin/templates/scripts/cordova/Api.js

* Converted the `Api` function to class
* Merged all the `cordova-common` `require` blocks.
* Cleanup syntax of `getPlatformInfo`
- `npm t`

refactor: Api class

---

bin/templates/project/__PROJECT_NAME__/Classes/MainViewController.h

iOS
This work was missed in https://github.com/apache/cordova-ios/pull/1161 and is now causing errors.
Removed unused headers from the project template.
Unit tests pass (although they also didn't catch this being an error last time)

chore: Remove unused imports from template

---

tests/spec/create.spec.js

The tests did not wait for the promises of the test operations to resolve. That's why our CI did not fail for #1161 and we needed to fix that PR up in #1173.
This PR makes the tests wait for the build to finish and sets appropriate timeouts. Of course, this will result in longer CI run times.

fix(spec/create): handle createAndBuild promises

---

tests/spec/create.spec.js

Of course, the first CI run _after_ merging #1171 had tests that timed out :unamused: So let's hope that doubling the timeout will prevent that.

test(create): increase test timeout

---

bin/create

Set failing exit code on failure for `bin/create`, like we do for the other binaries.

fix(bin/create): set failing exit code on failure

---

tests/spec/create.spec.js

This should speed up the create tests by a few minutes while still allowing us to notice if any part of the build had issues regarding special characters.

test(create): waste less time on name variants

---

tests/spec/create.spec.js

The duration of the create tests seems to be highly variant. Probably influenced by GH Action runner load. This PR increases the timeouts generously to avoid premature test cancellation.

test(create): further increase timeouts to avoid false negatives

---

bin/apple_ios_version
bin/apple_osx_version
bin/apple_xcode_version
bin/templates/scripts/cordova/lib/versions.js
tests/spec/unit/versions.spec.js

This removes some minor code smells from the `versions` module and binaries.
- all version getters in `versions`  now actually return the version; previously 2 of them logged it directly
- a common helper method is used to create the legacy version binaries
- automated tests pass
- version binaries still work (checked manually)

refactor(versions): DRY version binary code

---

bin/templates/scripts/cordova/lib/versions.js

Only log error messages instead of the whole error objects in case of failure. This improves output especially for child process errors.
Manual testing

feat(versions): print error messages, not error objects

---

bin/templates/scripts/cordova/lib/run.js

Just some code quality improvements

refactor(run): code cleanup

---

bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/run.js

This makes build and run modules more closed by avoiding to expose
internals via the resolved promise value. Both modules' main exports
previously returned a promise that resolved to a subrocess spawn result.
Now these promises resolve to undefined.
The public API methods that return these promises did not document a
specific promise return value, just when the promise would resolve or
reject. Thus, this change is not breaking.

refactor: hide implementations of build & run

---

.eslintrc.yml
bin/apple_ios_version
bin/apple_osx_version
bin/apple_xcode_version
bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/listEmulatorBuildTargets.js
bin/templates/scripts/cordova/lib/listEmulatorImages.js
package-lock.json
package.json

Update Eslint Config with Fixes
- `@cordova/eslint-config@^4.0.0`
- applied auto corrections
- applied manual corrections
- prefer-regex-literals
- `npm t`

dep!(dev): bump eslint w/ corrections

---

bin/templates/scripts/cordova/lib/Podfile.js
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/clean.js
bin/templates/scripts/cordova/lib/listDevices.js
bin/templates/scripts/cordova/lib/listEmulatorBuildTargets.js
bin/templates/scripts/cordova/lib/run.js
bin/templates/scripts/cordova/lib/versions.js
package-lock.json
package.json
tests/spec/unit/lib/list-devices.spec.js

Progresses https://github.com/apache/cordova/issues/16 and https://github.com/apache/cordova/issues/7
Use `execa` for any subprocess spawning.
`execa` has no equivalent of `superspawn`'s `printCommand` option (if set to `true`, it emits a verbose log of the command being executed). In the current state of this PR, those verbose logs are removed without a substitute.
`superspawn` promises resolve to the captured stdout, while `execa` resolves to an object with more properties. In many of the cases where we spawn subprocesses, this does not matter, since we we only care about promise fulfillment.
`superspawn` allowed to subscribe to a running process' output by means of Q's `progress` method. This basically directly translates to subscribing to `data` events on the backing streams. So that …

refactor: replace superspawn with execa

---

bin/lib/create.js

This takes the changes from the first four commits of #1191 and adds a few further simplifications in the affected code areas.
I pulled this out to reduce the scope of said PR and since I already reviewed this part of the changes.
From #1191:
- Remove exported `updateSubprojectHelp`
- Remove exported `update_cordova_subproject`
- Renamed internal function `update_cordova_subproject` to `updateCordovaSubproject`
- Refactored internal function `updateCordovaSubproject` to take in two static arguments:
- `projectXcodePath` which is the path to project's xcodeproj
- `cordovaLibXcodePath` which is the path to the CordovaLib's xcodeproj. (Note: it maybe a symbolic link when `--link` flag is added when installing platform)
- Improved comments
- Removed excessive supportive internal methods
- …

refactor: cleanup create script

---

bin/lib/create.js
bin/templates/scripts/cordova/apple_ios_version
bin/templates/scripts/cordova/apple_osx_version
bin/templates/scripts/cordova/apple_xcode_version

This is a replacement for commit https://github.com/apache/cordova-ios/pull/1191/commits/daac0c1789231a2810519be2a0961ebeae9b6347 from #1191 which is broken in my opinion.
In contrast to the original commit, this moves the binaries to the current script template location `bin/templates/scripts/cordova`. This folder and its contents can be restructured and moved in a later PR.
`npm t`

refactor(create)!: move apple_* binaries & cleanup copyScripts

---

bin/lib/create.js

This further cleans up the create module, this time focusing on the module entry function, `createProject`.
There should only be minor behavioral changes:
- method is 100% `async` by marking it as such
- log output slightly simplified
- does not fail anymore if parent of target dir does not exist
`npm t`

refactor(create): cleanup createProject

---

bin/lib/create.js

The new order should make it easier to read the module top-down.
This change is isolated into its own PR since the diff is not really helpful.
This only moves functions around. No other changes.
`npm t`

refactor(create): sort functions in breadth-first call order

---

bin/lib/create.js

Last PR of @erisu's and my `create` cleanup effort.
Note: Ignore whitespace when viewing the diff.
This converts the create implementation to a class, so we can avoid excessive argument passing.
`npm t`

refactor(create): convert main implementation to class

---

bin/templates/scripts/cordova/Api.js
bin/templates/scripts/cordova/lib/build.js
bin/templates/scripts/cordova/lib/clean.js
bin/templates/scripts/cordova/lib/prepare.js
bin/templates/scripts/cordova/lib/run.js
tests/spec/create.spec.js

The goal of this PR is to eliminate all areas where our JS library expects to be located inside the project directory.
This is to prepare for a change that will keep the library in `node_modules` and not copy it to the platform project.
Basically this passes the project root that has been passed to `Api` to all places that need it but do not yet have it.
~~This also extends the E2E tests to check that we do not have to require the Api from the platform project folder.~~
- `npm t`

refactor: do not infer project root from script location

---

lib/build.js

iOS
Rebase against the main branch this pull request https://github.com/apache/cordova-ios/pull/956
Closes #956

feat: support multiple provisioning profiles

---

.github/workflows/ci.yml

iOS
Node 10 and 12 is already EOL.
Updated ci.yml.
Removed node 10.x and 12.x.
Added node 16.x and 18.x.
Supported versions are 14.x, 16.x, and 18.x.

ci: remove Node 10-12 & added Node 16-18

---

lib/build.js

Support extending the `exportOptions` through the `buildOpts`.
Resolves #1209

feat: support extending export options

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

iOS
With the introduction of iOS 16.4 WKWebView instances will no longer be inspectable by default.
Details: [Enabling the Inspection of Web Content in Apps](https://webkit.org/blog/13936/enabling-the-inspection-of-web-content-in-apps/)
This PR honors that change for Release builds, but explicitly sets the inspectability to `YES` for Debug builds by default.
It also introduce an override option, so consumers can influence this decision in their own build.
Tested the code in one of our own apps.

Set webView.inspectable to true for debug builds on iOS >= 16.4

---

lib/build.js
tests/spec/unit/build.spec.js

iOS
This enables automatic provisioning with Apple Cloud Distribution certificates (which is really useful for cloud CI systems).
This adds 3 new properties that can be specified on the command-line or via build.json, matching the 3 properties that need to be passed to xcodebuild to allow automatic cloud signing.
I have some notes about how this works and how I set up automatic signing with GitHub Actions for a non-Cordova project here: https://gist.github.com/dpogue/d11df53cca6ba0e23d14d674ee5f9762
Unit tests updated, still needs some further testing.

feat: Add support for Apple Cloud Distribution signing

---

CordovaLib/Classes/Public/CDVPlugin.m
tests/CordovaLibTests/CDVPluginInitTests.m
tests/CordovaLibTests/CordovaLibApp/SwiftInitPlugin.swift
tests/CordovaLibTests/CordovaLibApp/config.xml
tests/CordovaLibTests/CordovaLibTests.xcodeproj/project.pbxproj

iOS
Fixes #1288 
This ensures that the default `init` method is called for CDVPlugin subclasses, to allow Swift initializers to run as expected.
Aside: I still feel like `NS_DESIGNATED_INITIALIZER` would be the theoretically correct way to solve this, but that doesn't work when our designated initializer with the webview is part of private implementation details (your designated initializer must be part of your public API surface).
The risk is that someone could (in their own code) do `[[MyCordovaPlugin alloc] init]` and try to construct a plugin instance without providing the webview engine, and lead to all sorts of weird issues.
However, that problem already existed and people don't seem to be shooting themselves in the foot with it (or at least, not complaining here when they do), so …

fix(CDVPlugin): Swift init

---

.github/workflows/ci.yml

CI
non-darwin jobs is still testing with NodeJS 14 which isn't a supported environment anymore since https://github.com/apache/cordova-ios/pull/1305
Dropped NodeJS 14 from non-darwin test matrix.
CI will do it's thing.

fix(ci): Drop NodeJS 14 tests for non-darwin jobs

---

.github/workflows/ci.yml

ios
Node 20 has been released, we should get it in our test matrix to identify any issues before the next major release.
Adds Node 20 to the CI test matrix.
Adds Node 20 to the CI test matrix.

ci: add node 20.x

---

CordovaLib/Classes/Public/CDVViewController.m

ios
Closes #1231.
Add constraints to the splashscreen view so that it keeps the aspect ratio and positioning when the device is rotated.
@goffioul This is mostly the code that you proposed, do you want to be credited on the commit for this?
Tested on an iOS Simulator.

fix(splashscreen): positioning after rotation

---

lib/Api.js
lib/run.js
package.json
templates/cordova/lib/list-devices
templates/cordova/lib/list-emulator-images
tests/spec/unit/Api.spec.js
tests/spec/unit/lib/run.spec.js

n/a
Support calling for listTarget on the PlatformAPI.
Will be used by Cordova CLI/Lib 12
Reverted the location of the binraries to the original location. Needed for older CLI versions. 
Added `listTargets` on platform api and added supporting methods in the `run.js` file
`npm t`

feat: add listTarget api & revert original bin file location

---

CordovaLib/include/Cordova/CDVURLSchemeHandler.h

iOS
I am using Cordova inside a React Native application so I often need to destroy and re-create the CDVViewController.
Since I am using a custom scheme, it is leaking (the CDVViewController is never deallocated despite being remove from its parentViewController)
I confirm that by changing strong to weak, the CDVViewController is deallocated as soon as it is removed from its parent view controller.
- [yes] I've run the tests to see all new and existing tests pass
- [no] I added automated test coverage as appropriate for this change
- [yes ] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [no ] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using …

(ios) fix: memory leak when removing the CDVViewController

---

lib/build.js
lib/run.js
tests/spec/unit/build.spec.js

iOS
Specifying `CONFIGURATION_BUILD_DIR` can cause issues with Cocoapods.
Closes #617
Closes #659
Closes #671
Once upon a time, Xcode's default directory values had issues when there were spaces in project names, so we override the `CONFIGURATION_BUILD_DIR` and `SHARED_PRECOMPS_DIR` variables with our own paths.
However, this can interfere with Cocoapods, and Xcode should be able to handle things sensibly nowadays.
Unfortunately, that results in our build artifacts living somewhere in a randomly-named Xcode DerivedData directory, and then we can't do things like run the app in a simulator or on a device because we don't know the path to it. 🤦🏼‍♂️ 
Setting `SYMROOT` allows us to control the output directory of the built products, with the caveat that Xcode always creates a subdirectory …

feat!: remove default build dir overrides

---

CordovaLib/Classes/Public/CDVViewController.m
templates/cordova/defaults.xml
templates/project/__PROJECT_NAME__/config.xml
tests/CordovaLibTests/CordovaLibApp/config.xml
tests/spec/unit/fixtures/ios-config-xml/SampleApp/config.xml
tests/spec/unit/fixtures/ios-config-xml/cordova/defaults.xml

Fixes #1332.
iOS
This preference is unused (since at least the move from UIWebView to WKWebView)
Remove some special handling that was being done in CDVViewController for an unused BackupWebStorage preference.
Unit tests pass.

chore: Remove unused BackupWebStorage preference

---

lib/Api.js

ios
Resolve issue #1125 
Replace variables with the variable value for all specs of pod
I tested with custom plugin adding plugin with variables for all pod specs available(git, tag, branch, commit and spec)
https://guides.cocoapods.org/using/the-podfile.html

fix: replace of podspec variables in podfile #1125

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/cordova.js

IOS
Currently there is no option to set the limitsNavigationsToAppBoundDomains attribute from the `config.xml`.  If you want to use cookie authentication or browser APIs you want to set this to `YES`.
Official documentation: https://webkit.org/blog/10882/app-bound-domains/
This changeset is copied from this tutorial: https://www.ryseapp.io/blog/engineering/step-by-step-guide-to-setup-and-configure-cordova-for-ios-and-android-to-load-a-hosted-react-app
Tested on multiple simulator instances and and physical hardware. Without it the cookie authentication for a single domain will not work. After I add this change the authentication works.

feat: Add LimitsNavigationsToAppBoundDomains configuration key

---

lib/Api.js
lib/PodsJson.js
lib/prepare.js

fix: Try updating Podfile deployment target on prepare

---

CordovaLib/include/Cordova/CDVAvailability.h

This is supposedly done by coho during the release process, but looks like last two releases failed to do it, so the versions are missing.
EDIT: 
CDVAvailability.h file was moved, so the code in coho was not working, I've updated the path on coho
https://github.com/apache/cordova-coho/pull/323

fix: Add missing cordova versions to CDVAvailability.h

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

Cordova still supports Xcode 11 technically since we have not officially dropped support for it, but this code doesn't compile on Xcode 11, making paramedic to fail.
The PR puts the code inside a `__IPHONE_OS_VERSION_MAX_ALLOWED` version check so it compiles.

chore: make code compile on Xcode 11

---

templates/project/__PROJECT_NAME__.xcodeproj/project.pbxproj

iOS
Closes GH-1357.
After moving some files around in cordova-ios 7.0.0, Xcode opted to use a `name` attribute in the Xcode project file rather than a `path` attribute. This is valid from Xcode's perspective, but fails expectations of the `node-xcode` library that we use for manipulating the project file.
Ensure that every file in the project has an explicit `path` specified.
...

fix: Ensure Xcode project file references use path

---

lib/check_reqs.js

in cordova-ios 6 the project was updated to Xcode 11, so Xcode/xcodebuild 11 is required, but the version check was not bumped, so bumping it now.

chore: Bump xcodebuild version check to 11

---

templates/project/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist

iOS
Fixes #1370 where WebAssembly cannot be loaded in iOS production build due to the error `"Unexpected response MIME type. Expected 'application/wasm'"`. The error causes a blank app screen and prevents any user interaction.
I added `UTExportedTypeDeclarations` to the Info.plist template file, specifying the expected MIME type for loading WASM files.
I modified my project's Info.plist file by adding the `UTExportedTypeDeclarations` key and value as shown in the commit, built and ran my project on the device, and verified that the app loads and is displayed as expected.
The automated tests don't run on my macOS version as it does not match CordovaLibTests’s deployment target. I don't know how to get the tests running.

fix: WASM MIME type error by specifying it in Info.plist template

---

Cordova.podspec
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/Info.plist
CordovaLib/PrivacyInfo.xcprivacy
CordovaLib/include/Cordova/CDV.h
CordovaLib/include/Cordova/Cordova.h
Package.swift
lib/create.js
templates/project/__PROJECT_NAME__.xcodeproj/project.pbxproj
templates/project/__PROJECT_NAME__/Bridging-Header.h
templates/project/__PROJECT_NAME__/PrivacyInfo.xcprivacy

iOS
Starting in April 2024, Apple requires that newly submitted apps include a Privacy Manifest that declares whether the app collects personal data, whether it uses that data for tracking purposes, and whether the app uses privacy-impacting system APIs.
Adds a PrivacyInfo.xcprivacy manifest file to CordovaLib, declaring that CordovaLib does not do any tracking or use any privacy-impacting APIs.
Adds a PrivacyInfo.xcprivacy manifest file to the generated app template, with empty declarations. It is up to the app author to provide the correct privacy details for their application.
Minor cleanups to the CordovaLib project to improve both Xcode subproject and Swift package use.
Tested locally in Xcode.

feat: add PrivacyInfo.xcprivacy for CordovaLib & app template

---

lib/build.js

ios
resolves #823 
resolves #536
cherry-picked changes from https://github.com/apache/cordova-ios/pull/823 and rebase with lastest main branch
n/a

fix: use PROVISIONING_PROFILE_SPECIFIER for manual codesigning

---

lib/ConfigParseriOS.js
lib/PlatformConfigParser.js
lib/prepare.js
package-lock.json
package.json
tests/spec/unit/fixtures/prepare/no-privacy-manifest.xml
tests/spec/unit/fixtures/prepare/privacy-manifest.xml
tests/spec/unit/prepare.spec.js

ios
To support setting ios privacy manifest according to config.xml setting.
Introducing <privacy-manifest> tag in config.xml ios platform directive.
If user add following directive in config.xml (platform ios)
```
<privacy-manifest>
<key>NSPrivacyTracking</key>
<true/>
<key>NSPrivacyCollectedDataTypes</key>
<array/>
<key>NSPrivacyAccessedAPITypes</key>
<array/>
<key>NSPrivacyTrackingDomains</key>
<array/>
</privacy-manifest>
```
the ios project PrivacyManifest.xcprivacy is updated as config.xml.
If user does not set `<privacy-manifest>` tag in config.xml, the cordova template 
default PrivacyManifest.xcprivacy is used.
Note: This `<privacy-manifest>` tag overrides whole PrivacyManifest.xcprivacy file in project each time 
user execute cordova prepare.
I locally checked this feature with …

feat: add privacy-manifest config support

---

.github/workflows/ci.yml
package.json
tests/CordovaLibTests/CDVPluginInitTests.m

iOS
Tests would fail to run in Xcode 15 due to not having a iPhone 8 simulator with the latest runtime, and `CONFIGURATION_BUILD_DIR` was causing errors about Cordova.framework not being found and sometimes warnings about stale files.
* Move macOS CI to run on macOS 14 on Apple Silicon, using Xcode 15
* Set the tests to run with an iPhone 15 simulator
* Fix a warning about a missing cast to `AppDelegate*`
* Set `-derivedDataPath` rather than `CONFIGURATION_BUILD_DIR` so that Apple doesn't cache stale data about previous runs
Ran in GitHub CI and locally with latest Xcode 15

chore(ci): Fix ObjC testing with latest Xcode

---

CordovaLib/Classes/Public/CDVViewController.m
lib/prepare.js
templates/project/__PROJECT_NAME__/Assets.xcassets/SplashScreenBackgroundColor.colorset/Contents.json
templates/project/__PROJECT_NAME__/CDVLaunchScreen.storyboard
tests/spec/unit/fixtures/ios-config-xml/SampleApp/Assets.xcassets/SplashScreenBackgroundColor.colorset/Contents.json

iOS
Closes #1254.
Support a `SplashScreenBackgroundColor` preference that sets the background colour of the splash screen via xcassets.
If no `SplashScreenBackgroundColor` is provided, it will fall back to the `BackgroundColor` (i.e., the current behaviour). 
If neither are specified, it will fallback to the system background colour (also current behaviour).
* Created a new iOS project from this branch and specified both the `BackgroundColor` and `SplashScreenBackgroundColor` preferences. Ensured both variables had correct values in Xcode and confirmed splash screen used the correct colour on device.
* Created a new iOS project from this branch and specified only the `BackgroundColor` preference. Ensured both variables had correct values in Xcode and confirmed splash screen used the …

feat: SplashScreen Background Color preference support

---

.eslintrc.yml
.github/workflows/ci.yml
lib/Api.js
lib/BridgingHeader.js
lib/Podfile.js
lib/PodsJson.js
lib/build.js
lib/clean.js
lib/create.js
lib/plugman/pluginHandlers.js
lib/prepare.js
lib/projectFile.js
lib/run.js
package-lock.json
package.json
tests/spec/createAndBuild.spec.js
tests/spec/unit/Api.spec.js
tests/spec/unit/BridgingHeader.spec.js
tests/spec/unit/Plugman/common.spec.js
tests/spec/unit/Plugman/pluginHandler.spec.js
tests/spec/unit/Podfile.spec.js
tests/spec/unit/PodsJson.spec.js
tests/spec/unit/build.spec.js
tests/spec/unit/create.spec.js
tests/spec/unit/lib/list-devices.spec.js
tests/spec/unit/pluginAdd.spec.js
tests/spec/unit/prepare.spec.js
tests/spec/unit/preparePlatform.spec.js
tests/spec/unit/projectFile.spec.js

iOS
This allows us to drop the `fs-extra` and `unorm` library by replacing their use with built-in NodeJS standard library calls.
* Replace `unorm` module with `String.prototype.normalize`
* Replace `fs-extra` usage with equivalent NodeJS `fs` calls
* Upgrade `which` to latest version
* Use `path.join` in a bunch of spots where we're constructing paths
* Remove the (unused) `nopt` dependency

chore(deps): Modernize some dependencies

---

CordovaLib/Classes/Public/CDVViewController.m

iOS
Fixes GH-1423 (based on the comment on https://github.com/apache/cordova-ios/commit/4c8136345ae9622646ee7e4eb60ba2b37ad44fbe#r142043240)
Check that the engine class instance responds to the `initWithFrame:configuration:` selector rather than the engine class itself (because it's not a static class method).
All unit tests pass, but I don't think we have test coverage for this particular feature.

fix: Properly set the WebView config when it is provided

---

templates/cordova/apple_ios_version
templates/cordova/apple_osx_version
templates/cordova/apple_xcode_version

iOS
Fixes GH-1415
Fixes GH-1432
The bin scripts in the template needed to be updated to refer to the cordova-ios internals as a node module instead of as loose files in the same directory.
All unit tests pass.

fix: Fix version checking helper scripts

---

lib/plugman/pluginHandlers.js
tests/spec/unit/Plugman/pluginHandler.spec.js

Alternative to #1444 that fixes the tests instead of adding a new function
closes https://github.com/apache/cordova-ios/pull/1444
closes https://github.com/apache/cordova-ios/issues/1443

fix: uninstall plugin with asset tag

---

CordovaLib/Classes/Private/Plugins/CDVLaunchScreen/CDVLaunchScreen.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVAppDelegate.m
CordovaLib/Classes/Public/CDVCommandQueue.m
CordovaLib/Classes/Public/CDVPlugin.m
CordovaLib/Classes/Public/CDVPluginResult.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/include/Cordova/CDVAppDelegate.h
CordovaLib/include/Cordova/CDVAvailabilityDeprecated.h
CordovaLib/include/Cordova/CDVPlugin.h
CordovaLib/include/Cordova/CDVPluginResult.h
CordovaLib/include/Cordova/CDVScreenOrientationDelegate.h
CordovaLib/include/Cordova/CDVURLSchemeHandler.h
CordovaLib/include/Cordova/CDVViewController.h
CordovaLib/include/Cordova/CDVWebViewEngineProtocol.h
tests/CordovaLibTests/CDVPluginInitTests.m
tests/CordovaLibTests/CordovaLibApp/AppDelegate.h
tests/CordovaLibTests/CordovaLibApp/AppDelegate.m

iOS
Closes #1428.
* Added deprecation annotations to things we want to discourage people from using (some of these can be removed in Cordova iOS 9)
* Remove some conditionals for iOS versions pre-11 and dead code
* Change CDVPlugin's `viewController` from a `UIViewController*` to a `CDVViewController*`
* Move a webview engine-related delegate to a header that makes more sense
Unit tests pass.

refactor!: Easy deprecation cleanups

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

iOS
Closes #920.
Ensure that we remove the WKWebView script message handler when the web view plugin is disposed. Otherwise it stays in memory holding references to stuff.
Tests pass

fix: Fix memory leak from user script handler

---

lib/check_reqs.js

Closes https://github.com/apache/cordova-ios/issues/1367
~we could even drop Xcode 14 and go to 15 directly since Apple is going to require Xcode 15 at some point this month~

chore!: Bump minimum Xcode version to 15

---

.github/workflows/ci.yml
package-lock.json
package.json

iOS
Node 16 is EOL and Node 22 will be LTS in October.
* Dropped Node 16 from CI testing
* Added Node 22 to CI testing
* Updated `nyc`, `jasmine`, and `rewire` deps to latest versions
Technically all the breaking dependency updates were only in devDependencies, so the platform should still work for end users on Node 16, but we're not testing that in CI anymore so we will have no way of making any such guarantees.
All existing tests pass.

chore!: Bump NodeJS versions in CI & update deps

---

lib/build.js
tests/spec/unit/build.spec.js

iOS
Closes GH-526.
Closes GH-1366.
Closes GH-1377.
Closes GH-1469.
Changed `getDefaultSimulatorTarget()` to reject with an error message when no simulators are found.
This should at least return a useful and actionable error message to the end user, rather than "Cannot read property name of undefined".
Existing unit tests pass.
Added unit test to confirm the function now rejects when no simulators are present.

fix: Error when no simulators are available

---

lib/Api.js

iOS
Closes GH-1365.
Calling `new Podfile(...)` will create an empty Podfile in the project if it does not exist. If we don't have any pods to add for a given plugin, we can skip doing anything at all with the Podfile and avoid needlessly creating it.
Note: I moved an `if` block to do an early return, which de-indented the majority of the code in that function. This PR is easier to review with whitespace changes disabled.
Tested manually by creating a new project and installing the `cordova-plugin-inappbrowser` and confirmed that no Podfile was present in the `platforms/ios` directory.

fix(Podfile): Avoid creating an empty Podfile on plugin install

---

CordovaLib/Classes/Private/CDVCommandDelegateImpl.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVSettingsDictionary.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/Classes/Public/NSDictionary+CordovaPreferences.m
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/include/Cordova/CDV.h
CordovaLib/include/Cordova/CDVCommandDelegate.h
CordovaLib/include/Cordova/CDVPlugin.h
CordovaLib/include/Cordova/CDVSettingsDictionary.h
CordovaLib/include/Cordova/CDVViewController.h
CordovaLib/include/Cordova/NSDictionary+CordovaPreferences.h
tests/CordovaLibTests/CDVSettingsDictionarySwiftTests.swift
tests/CordovaLibTests/CDVSettingsDictionaryTests.m
tests/CordovaLibTests/CDVWebViewEngineTest.m
tests/CordovaLibTests/CordovaLibTests.xcodeproj/project.pbxproj

iOS
This will replace the extension category on NSDictionary, which has always felt a little bit hacky and has caused issues in weird circumstances due to requiring special build flags to work properly.
Add a new `CDVSettingsDictionary` class that is used for accessing preferences.
Yes, subclassing `NSDictionary` is generally considered a bad idea because the internal implementation details are weird and cause problems. However, in this case we're essentially wrapping a real `NSMutableDictionary` and proxying everything to it, so this _should_ work the way we'd expect it to.
Added new unit test providing coverage for all the CDVSettingsDictionary methods.
Added a test file to check Swift behaviour as well, but adding it to the test suite project doesn't work (weird Xcode swift errors). …

refactor!: Add CDVSettingsDictionary class

---

CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVAllowList.m
tests/CordovaLibTests/CDVAllowListTests.m

iOS
These may be unusual schemes, but they are canonically valid and should be supported.
Closes GH-1291.
Update the regex in `CDVAllowList` to the one @erisu suggested.
Added a test case to confirm the schemes are parsed properly.

fix: Update CDVAllowList to support more valid schemes

---

CordovaLib/Classes/Private/CDVCommandDelegateImpl.m
CordovaLib/Classes/Public/CDVURLSchemeHandler.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/include/Cordova/CDVViewController.h
tests/CordovaLibTests/CordovaLibApp/AppDelegate.m

iOS
A bunch of properties on CDVViewController were publicly exposing internal state that should be private to the instance. We can't completely solve that problem right now, but we can make the API boundary more clearly delineated.
Clean up properties/ivars in CDVViewController
Rename wwwFolderName to webContentFolderName so that it gets a useful label in Xcode's Interface Builder for people embedding CDVViewController inside their own apps (IB showed it as "Www Folder Name" and there's no way to alias that, so now it shows up as "Web Content Folder Name")
Existing tests pass.

refactor: Clean up properties/ivars in CDVViewController

---

CordovaLib/include/Cordova/CDVPlugin.h

iOS
As mentioned in #1399, this API was added as a compatibility shim at the time we supported both UIWebView and WKWebView, when WKWebView did not expose a public `scrollView` property. That property was made available in iOS 8, and this extension now risks causing problems due to being applied globally to all UIView subclasses.
Closes #1399.
Deprecate the category extension to expose a `scrollView` property on all UIView object instances, and remove it entirely from visibility to Swift.
* Existing tests pass.
* Tested against all core Apache plugins.
* Manually tested that this resolves the issue in #1399 where a Swift UIView subclass defines a `scrollView` property

fix!: Deprecate(/Remove) scrollView category extension on UIView

---

CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/include/Cordova/CDVViewController.h

iOS
Methods in CDVViewController are spread all over with no logical grouping to make them easier to find.
This gives them a much more logical grouping.
All existing tests passed (no functional change, just moving functions around)

refactor: Reorder methods in CDVViewController

---

CordovaLib/Classes/Private/Plugins/CDVLaunchScreen/CDVLaunchScreen.m
CordovaLib/Classes/Public/CDVCommandQueue.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/CordovaLib.docc/CordovaLib.md
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/include/Cordova/CDVCommandDelegate.h
CordovaLib/include/Cordova/CDVPlugin.h
CordovaLib/include/Cordova/CDVPluginResult.h
CordovaLib/include/Cordova/CDVScreenOrientationDelegate.h
CordovaLib/include/Cordova/CDVViewController.h
CordovaLib/include/Cordova/Cordova.h
CordovaLib/include/Cordova/NSMutableArray+QueueAdditions.h

iOS
The API available to people embedding CordovaLib as a framework in their existing apps is not well documented, nor is the API available to plugin authors.
With DocC comments, we can generate Apple-style documentation for our framework, and serve it on GitHub Pages.
Add DocC comments to some of CordovaLib and add a main page file. This is only an initial pass over the sections of code that I've been touching recently, but the goal is to have everything that's public API commented appropriately.
Existing tests pass.
Built documentation bundle with Xcode for local testing.

docs(CordovaLib): Start filling out DocC comments

---

CordovaLib/include/Cordova/CDV.h

iOS
Plugins that included only `<Cordova/CDV.h>` were seeing issues around extending `CDVPlugin`.
Make `CDV.h` consistently import `Cordova.h` to define the full module.
The fact that there's a circular dependency between the headers isn't actually a problem in Objective-C because it uses `#import` rather than `#include` and the compiler ensures each header is only included once.
Somehow that was also causing it to only evaluate the header once and not differentiate imports where the macro was defined vs not defined.
Compiled a test app whose plugins used `#import <Cordova/CDV.h>` and were broken before this change.

fix: CDV.h wasn't bringing in Cordova.h consistently

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVURLSchemeHandler.h
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVURLSchemeHandler.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/Classes/Public/CDVWebViewProcessPoolFactory.m
CordovaLib/CordovaLib.docc/CordovaLib.md
CordovaLib/include/Cordova/CDVPlugin.h
CordovaLib/include/Cordova/CDVViewController.h
CordovaLib/include/Cordova/CDVWebViewEngineProtocol.h
CordovaLib/include/Cordova/CDVWebViewProcessPoolFactory.h
CordovaLib/include/Cordova/NSDictionary+CordovaPreferences.h

iOS
Existing behaviour for plugins to opt-in to handling custom scheme resource loads was not documented and there were some unsafe assumptions around only a single plugin handling all requests.
Add a `CDVPluginSchemeHandler` protocol to allow plugins to declare that they want to intercept WebKit resource loads.  
We don't rely on the protocol itself being implemented by the plugins (we continue to check with `-respondsToSelector:`) but this allows us to avoid `objc_msgSend` and provides a way to document some of this plugin behaviour that is not otherwise explained.
Also, use a `NSMapTable` to associate plugin instances with the request being handled. Since we loop over the plugins, there's a chance that multiple plugins might want to handle different requests (which sounds like a …

refactor: Define a protocol for scheme-handling plugins

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewUIDelegate.h
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewUIDelegate.m

iOS
Closes GH-1120.
Closes GH-1121.
Closes GH-1429.
In cases where the system was presenting something on the screen (such as a permission prompt, or an undo dialog) or in cases where the `CDVViewController` was not the root view controller (such as in a tabbed navigator), trying to show any dialogs triggered from the WebView would attempt to create an alert on the root view controller and get the view hierarchy into a bad state.
Now, we only try to display alerts on the `CDVViewController` that owns the WebView. This means that alerts can potentially end up behind other system dialogs, but the view controller no longer freezes.
(As an aside, having access to the `CDVViewController` here will be helpful for some future things too...)
Tested manually by triggering an alert while a …

fix: alerts could freeze the application

---

Cordova.podspec
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/CordovaLib.xcodeproj/xcshareddata/xcschemes/Cordova.xcscheme
Package.swift
lib/Podfile.js
tests/CordovaLibTests/CordovaLibTests.xcodeproj/project.pbxproj
tests/spec/unit/fixtures/icon-support/configs/multi.xml
tests/spec/unit/fixtures/icon-support/configs/none.xml
tests/spec/unit/fixtures/icon-support/configs/single-only.xml
tests/spec/unit/fixtures/icon-support/configs/single-variants.xml
tests/spec/unit/fixtures/ios-config-xml/SampleApp.xcodeproj/project.pbxproj
tests/spec/unit/fixtures/launch-storyboard-support/configs/legacy-only.xml
tests/spec/unit/fixtures/launch-storyboard-support/configs/modern-and-legacy.xml
tests/spec/unit/fixtures/launch-storyboard-support/configs/modern-only.xml
tests/spec/unit/fixtures/launch-storyboard-support/configs/none.xml
tests/spec/unit/fixtures/test-config-2.xml
tests/spec/unit/fixtures/test-config-3.xml
tests/spec/unit/prepare.spec.js

iOS
We already bumped the app template to a minimum of iOS 13 to support UISceneDelegates, and it turns out iOS 13 is the first version where WKURLSchemeTask is properly thread-safe, so we might as well bump CordovaLib and silence that warning that people keep complaining about 🥲
Bump the minimum iOS target for CordovaLib to 13.0, and update tests/project files to match.
Closes #1427.
All existing tests pass, no warnings in Xcode.

chore!: Bump CordovaLib requirements to iOS 13+

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

iOS
Closes GH-959.
If the navigation was cancelled, don't show an error page. This can cause issues where a subsequent request never loads into the webview because the error page is being shown.
This was previously implemented back in the UIWebView days as CB-13222 in https://github.com/apache/cordova-ios/pull/334 and was then proposed in https://github.com/apache/cordova-plugin-wkwebview-engine/pull/84 for the WKWebView plugin, but that didn't get reviewed/merged before the repo was archived. The fix is still valid, so we'll port it to the current version of the WKWebView plugin.
All existing tests passed.

fix: Avoid showing error page on cancelled navigation

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVURLSchemeHandler.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/include/Cordova/CDVPlugin.h
CordovaLib/include/Cordova/CDVViewController.h

iOS
Improve memory usage and support range requests for resources loaded via a custom scheme.
Changed the implementation of CDVURLSchemeHandler to do file reading on a background thread in 4MiB chunks rather than trying to load entire files into memory. 4MiB should be sufficient for most HTML/CSS/JS files, while still being low enough to not cause iOS to freak out about memory usage.
Improved URL building for file paths to ensure that things like query strings don't end up affecting which file gets loaded from the filesystem. Closes GH-909.
Also, implement support for the Range header to load subsections of files (mostly used for audio/video files) to further improve memory usage. Closes GH-1033.
Existing tests pass. All content for the mobile spec testcase loaded properly with these …

feat(scheme-handler): Improve memory usage & Range support

---

.github/workflows/docs.yml

Actions-based publishing to GitHub Pages should now be enabled on this repo: https://issues.apache.org/jira/browse/INFRA-26070
iOS
If we're adding docs to our CordovaLib public API, we might as well make them available online for people.
Generates API documentation from the DocC code comments in CordovaLib, and publishes it to GitHub Pages.
Confirmed that this publishes correctly in my fork.

ci: Publish DocC documentation to GitHub pages

---

CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/include/Cordova/CDVAppDelegate.h

iOS
Some plugins expect to be able to access the applications's CDVViewController via the AppDelegate. While previously we guaranteed that the `viewController` property was set to a non-nil CDVViewController, there was never any guarantee that it was set to the CDVViewController that is actually displaying the app (particularly in cases such as apps using CordovaLib only for a few pages as part of a larger app).
We've attempted to deprecate the property here, but some plugins still rely on the assumption that it will be non-nil, so we are trying to maintain compatibility in the common case here by assigning to it when a CDVViewController is loaded. This means there are still times in the app lifecycle where the `viewController` property is nil, but the deprecation warning will hopefully …

fix(compat): Set the app delegate viewController for plugins

---

templates/project/App/AppDelegate.h
templates/project/App/AppDelegate.swift
templates/project/App/Bridging-Header.h
templates/project/App/MainViewController.h
templates/project/App/ViewController.swift

iOS
Hopefully closes GH-1487.
This uses "non-standard" Swift annotations, but they've been supported by the past few versions of Xcode and are in the process of being standardized. Most importantly, they work for what we need.
Ran unit tests.
Ran mobilespec tests.

fix(objc): Workaround for Swift/ObjC template issues

---

lib/listEmulatorBuildTargets.js
lib/run.js
tests/spec/unit/run.spec.js

iOS
I think I accidentally broke this during earlier refactoring for 8.0.0, but it was now trying to (and incorrectly) listing the simulator devices rather than the simulator device/runtime combinations.
Restore the correct listing for simulator devices/runtimes when using `cordova run ios --list`
Tested running `npx cordova run ios --list` and ensured the output matched between these changes and 7.1.1

fix(emulators): Fix listing emulator targets

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m

iOS
Addresses #1486 
Simply clears the _webViewEngine stored property in this class on ‘dispose’ so that it no longer retains a reference to the WKWebView after dispose. 
In the platform centered approach (e.g, adding cordova-ios to an otherwise native app) via a swift package, we can subclass CDVViewController and dispose all plugins when our ViewController is no longer in the view hierarchy.

fix: WKWebView leak in the platform centered approach

---

CordovaLib/CordovaLib.docc/CordovaLib.md
CordovaLib/CordovaLib.docc/upgrading-8.md
CordovaLib/include/Cordova/CDVAppDelegate.h
CordovaLib/include/Cordova/CDVConfigParser.h

Docs
We want to make the migration process easier for plugin authors who want to support Cordova iOS 8, in light of the deprecations and other breaking changes.
Adds an "Upgrading Plugins to Cordova iOS 8.x" article to the DocC documentation bundle. This will get published on GitHub Pages, as well as being available from within Xcode.
Built the documentation locally.

docs: Add upgrade guide for plugin authors for 8.x

---

lib/Api.js
lib/create.js
tests/spec/createAndBuild.spec.js
tests/spec/unit/create.spec.js
tests/spec/unit/fixtures/test-config-3.xml

iOS
This ensures that by the time plugin installation happens, the preferences from the root application config.xml can be read as expected.
Closes GH-1422.
Merge the app's config.xml into the defaults.xml at creation time for the platform config.xml.
Also removed comments about the `link` option since that's no longer relevant (with CordovaLib consumed as a Swift package, it is always linked).
Existing tests pass, and added a new unit test to verify new behaviour.

fix(create): Copy config.xml data during creation

---

.github/workflows/ci.yml
.github/workflows/release-audit.yml

all
Improve CI.
* Fix errors when dependabot PRs try to run tests in CI
* Add JavaScript code scanning with CodeQL
CodeQL doesn't support Objective C, and I tried enabling the Swift scanning but it caused everything to run so slowly that all the tests timed out. But we don't actually have much Swift code, do I doubt that it worth trying to enable that right now.
* Ran in CI, tests pass

chore(ci): Add code scanning & fix dependabot failures

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewUIDelegate.h
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewUIDelegate.m
templates/cordova/defaults.xml

iOS
resolves #1166 
If the app uses WebRTC, the user is initially prompted for permission twice, and then prompted again each time the app is restarted.
The solution is inspired by react:
https://github.com/react-native-webview/react-native-webview/pull/2257
I tested the changes in a project that is using WebRTC camera streaming.

(iOS) Avoid repetitive permission prompts

---

CordovaLib/Classes/Public/CDVPlugin.m
CordovaLib/Classes/Public/CDVViewController.m

macOS Catalyst
Closes GH-1491.
When showing a webview on macOS Catalyst, always position it below the titlebar when a titlebar is displayed. This has the side effect of making all the `safe-area-inset` values 0, regardless of the `viewport-fit` value.
Also adds a `HideDesktopTitlebar` preference to make the titlebar invisible on macOS Catalyst with content extending behind it. I named this in a generic way because it sounds like this should also be feasible to apply to the cordova-electron platform.
When using a preference to disable drawing the titlebar, `safe-area-inset` works as expected (but generally requires `viewport-fit=cover` to be specified).
Tested with `viewport-fit=cover` and `viewport-fit=contain` and measured the calculated `safe-area-inset-top` value.

fix(catalyst): Fix content behind titlebar

---

lib/check_reqs.js

Update tooling minimum requirements
- Bump `ios-deploy` minimum requirement to `>=1.12.2`
- Bump `cocoapods` minimum requirement to `>=1.16.0` 
n/a

feat: bump tooling minimum requirements

---

CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVIntentAndNavigationFilter.h
CordovaLib/Classes/Private/Plugins/CDVIntentAndNavigationFilter/CDVIntentAndNavigationFilter.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVPlugin.m
CordovaLib/CordovaLib.docc/CordovaLib.md
CordovaLib/CordovaLib.docc/upgrading-8.md
CordovaLib/include/Cordova/CDVPlugin.h

iOS
Closes GH-1212.
Closes GH-1272.
Closes GH-1333.
Adds protocols to formalize the methods that plugins should implement to interact with behaviour around authentication challenges and navigation decisions.
For navigation decisions, we now pass along the full navigation action details as a dictionary.
This also adds the ability for plugins to intercept and respond to server authentication challenges.
All existing tests pass.

feat(plugins): Better define plugin behaviour protocols

---

Package.swift
templates/project/App.xcodeproj/project.pbxproj

iOS
This ends up being less confusing for everyone because the resulting framework is named Cordova.framework and the header paths are all `<Cordova/*.h>` but currently you need to reference the Swift dependency as "CordovaLib" rather than "Cordova".
As far as I can tell from a quick search of public Package.swift files on GitHub, nobody has actually consumed this as a Swift package, so any breakage should be minimal and we should take the opportunity to do this right as part of the major version bump.
Existing tests pass.

refactor!(SPM): rename Swift package from CordovaLib to Cordova

---

lib/Api.js
lib/create.js
tests/spec/unit/create.spec.js

iOS
Pointing a relative path to CordovaLib in the node_modules folder means that the Xcode project is no longer self-contained, which is significant change in terms of assumptions people can make about the project files in CI environments (i.e., preparing all platforms once, then copying just the platform folders to different runners to build).
We now copy the CordovaLib folder into a `platforms/ios/packages` directory and point to it there. (We will need to do the same for SPM plugins, which sorta turns out to our advantage...)
As a side effect, it seemed worth bringing back the `--link` option to continue pointing to node_modules for easier development.
Tested with mobilespec and unit tests.

refactor(template): Copy CordovaLib into a packages folder

---

CordovaLib/include/Cordova/CDVPlugin.h

iOS
CDVPlugin's commandDelegate is a weak pointer, which means technically in Swift it should be an optional type that requires unwrapping. For some reason, it is not.
If the wrap the CDVPlugin class in the `ASSUME_NONNULL` macro, Swift suddenly starts enforcing that it's an optional, and this breaks all existing Swift plugins.
You aren't allowed to combine `weak` and `nonnull`, and all the properties in CDVPlugin are weak, so just... don't wrap it in `ASSUME_NONNULL` to make life easier for everyone 🙃
Tested with mobilespec (which fails on master and passes with this change)

fix(Swift): Nullability stuff broke Swift compatibility

---

.github/workflows/ci.yml
README.md
package-lock.json
package.json

iOS, Node
cordova-ios 8.0.0 was already targeting NodeJS 18.x and that's EOL as of next month, so we might as well just bump this to 20.x and update to the latest version of nopt and which. This also matches [the version bump](https://github.com/apache/cordova-android/pull/1789) going in to the next cordova-android major.
All existing tests passed locally.

feat!: bump node engine requirement >=20.5.0 & update deps

---

CordovaLib/Classes/Private/CDVViewController+Private.h
CordovaLib/Classes/Private/Plugins/CDVStatusBarInternal/CDVStatusBarInternal.h
CordovaLib/Classes/Private/Plugins/CDVStatusBarInternal/CDVStatusBarInternal.m
CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVPlugin.m
CordovaLib/Classes/Public/CDVViewController.m
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/include/Cordova/CDVViewController.h
cordova-js-src/platform.js
cordova-js-src/plugin/ios/statusbar.js
lib/prepare.js
templates/cordova/defaults.xml
templates/project/App/Assets.xcassets/StatusBarBackgroundColor.colorset/Contents.json
templates/project/App/Base.lproj/Main.storyboard
tests/spec/unit/fixtures/ios-config-xml/App/Assets.xcassets/StatusBarBackgroundColor.colorset/Contents.json
tests/spec/unit/fixtures/ios-config-xml/App/Base.lproj/Main.storyboard

iOS
Web content authors should have control over how the status bar is handled using the built-in web platform functionality for UI colouring and opting in to showing behind the status bar or not.
This adds a background behind the status bar automatically when a page does not request to extend itself behind the status bar using a meta tag with `viewport-fit=cover`. It automatically shows and hides as the value of the viewport-fit option changes.
On iOS 16.4 and newer, it will be coloured according to the meta `theme-color` tag, and a default colour can be set in the storyboard for a CDVViewController.
We expose a very basic JS API hanging off the existing `window.statusbar` property that allows controlling the visibility (of the status bar contents entirely, not just of the background …

feat(statusbar): Simple built-in status bar support

---

lib/BridgingHeader.js
tests/spec/unit/fixtures/test-Bridging-Header.h

iOS
Our fixture file for Bridging Header tests didn't contain a bunch of stuff that the Bridging Header code tries to handle, so that code was never properly tested.
Update the Bridging Header fixture file to include more comment types and inline comments and not have a final newline.
That missing newline ended up uncovering a bug in the Bridging Header code where headers from multiple plugins could end up on a single line without separation, so that edge case is also fixed now.
Ensured existing unit tests pass

test: Improve test coverage of Bridging Headers & fix edge case

---

.github/workflows/ci.yml
.github/workflows/release-audit.yml

iOS
Node 24 has been released
* Add NodeJS version 24 to the CI matrix since it's now been released
* Update the GHA workflows to explicitly declare what permissions they need, to reduce the scope of default permissions

ci: Add Node 24 to CI test matrix

---

templates/project/App/AppDelegate.swift
templates/project/App/ViewController.swift

Can't even go one Xcode minor version without new stuff getting deprecated 🙄
iOS
Fix some new Swift deprecation warnings about `@_objcImplementation`
Changed `@_objcImplementation` to `@objc @implementation` if we're using a Swift 6.1 compiler or newer.
To be fair, this is now an officially supported Swift feature rather than an experimental option, so this is better in the long run.
Confirmed that this builds without deprecation warnings in Xcode 16.4.

fix(swift): Fix some new Swift deprecation warnings

---

lib/plugman/pluginHandlers.js
tests/spec/unit/Plugman/pluginHandler.spec.js

iOS
Closes GH-1530.
Try to safely clean up empty directories when uninstalling plugin assets without always forcibly removing the plugin directory itself. This should provide better handling for cases where plugins have multiple assets that get added to the plugin folder.
The `removeFileAndParents` function is already used for uninstall plugin JS module files.
Updated existing tests (minimally) and they are passing.
Have not testing in an actual project with an affected plugin
(/cc @cdm-tao if you are able to give this a try and report back)

fix(plugins): Handle uninstalling multiple plugin assets

---

CordovaLib/CordovaLib.docc/upgrading-8.md

Update Cordova-iOS 8 upgrade docs to include the precompiled prefix header deprecation notice.
N/A

doc: add precompiled prefix header deprecation notice to 8.x upgrade

---

templates/project/App.xcodeproj/project.pbxproj

Resolves CocoaPods warning for potential problems with OTHER_LDFLAGS overrides.
```
[!] The `App [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-App/Pods-App.debug.xcconfig'. This can lead to problems with the CocoaPods installation
[!] The `App [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-App/Pods-App.release.xcconfig'. This can lead to problems with the CocoaPods installation
```
Updated following Debug & Release `buildSettings` in `App.xcodeproj/project.pbxproj`
From:
```
OTHER_LDFLAGS = (
"$(OTHER_LDFLAGS)",
"-ObjC",
);
```
To:
```
OTHER_LDFLAGS = (
"$(inherited)",
"-ObjC",
);
```
- Created a sample project
- Added the iOS platform with changes
- Added a plugin that has …

fix: potential problems overriding OTHER_LDFLAGS

---

package-lock.json
package.json

iOS
`nyc` is seemingly less maintained than we'd like, and brings in a bunch of dependencies we'd prefer to avoid.
Change from using `nyc` for code coverage to using `c8`
All existing tests pass and generate coverage information.

chore(coverage): Test using c8 for code coverage

---

CordovaLib/Classes/Private/Plugins/CDVWebViewEngine/CDVWebViewEngine.m
CordovaLib/Classes/Public/CDVWebViewProcessPoolFactory.m
CordovaLib/CordovaLib.docc/CordovaLib.md
CordovaLib/CordovaLib.docc/upgrading-8.md
CordovaLib/include/Cordova/CDVWebViewProcessPoolFactory.h

iOS
WKProcessPool has been marked as deprecated by Apple: https://developer.apple.com/documentation/webkit/wkprocesspool
> Creating and using multiple instances of WKProcessPool no longer has any effect.
Mark CDVWebViewProcessPoolFactory as deprecated in Cordova-iOS 8.
I guess technically since this is just a deprecation it's not a breaking change, but it makes sense to do this in a major version just to be safe. I'm not removing it because of plugins and it might still be needed on iOS 13 through 15, and we still technically support those.
Existing tests pass and CordovaLib builds without any warnings

refactor!: Deprecate CDVWebViewProcessPoolFactory

---

CordovaLib/CordovaLib.docc/upgrading-8.md

Simplified code examples for accessing scrollView property dynamically in Objective-C.
The code example for objective-c to access the deprecated scrollview was to complex and can be made easier.

Simplify Objective-C scrollView access in upgrading-8.md

---

CordovaLib/Classes/Public/CDVAppDelegate.m
CordovaLib/Classes/Public/CDVSceneDelegate.m
CordovaLib/CordovaLib.xcodeproj/project.pbxproj
CordovaLib/include/Cordova/CDVPlugin.h
CordovaLib/include/Cordova/CDVPluginNotifications.h
CordovaLib/include/Cordova/CDVSceneDelegate.h
CordovaLib/include/Cordova/Cordova.h
templates/project/App/SceneDelegate.swift

iOS
In cordova-ios 8 we've added a SceneDelegate to the generated template app, and in iOS 26 Apple starting to make UISceneDelegates mandatory.
In light of that, and deprecations around UIApplicationDelegate URL handling, it makes sense to have a Cordova UISceneDelegate class that does URL handling and exists as an extension point for plugins.
* Added `CDVSceneDelegate` as public API
* Changed the template to extend from `CDVSceneDelegate`
* Implemented URL handling in `CDVSceneDelegate` to fire `CDVPluginHandleOpenURLNotification`
* Refactored plugin notifications out into their own header file
Sample application builds and runs.

feat!: Add CDVSceneDelegate class as an extension point

---

CordovaLib/CordovaLib.docc/upgrading-8.md

- Clearify, that scrollView was originally added by Cordova
- Add discussion link for more details about the scrollView property

docs: Update deprecation notice for scrollView property in upgrading-8.md
