bin/templates/project/__CLI__.xcodeproj/project.pbxproj
bin/templates/project/__NON-CLI__.xcodeproj/project.pbxproj

[Jira issue](https://issues.apache.org/jira/browse/CB-9273)

CB-9273 "Copy www build phase" node is not found

---

bin/lib/create.js

[Jira issue](https://issues.apache.org/jira/browse/CB-9453)

CB-9453 Updating to iOS@3.9.0 not building

---

bin/templates/project/__PROJECT_NAME__/__PROJECT_NAME__-Info.plist

CB-9690 Can't submit iPad apps to the App Store for iOS 9

---

bin/templates/scripts/cordova/lib/copy-www-build-step.js

[Jira issue](https://issues.apache.org/jira/browse/CB-9698)

CB-9698 Add rsync error handling in ios copy-www-build-step.js

---

bin/templates/scripts/cordova/lib/run.js

Targets Added:
- iPhone-6s
- iPhone-6s-Plus
- iPad-Air-2
- iPad-Pro

Add additional valid targets for simulation

---

tests/spec/cordovalib.spec.js

Updates killall Simulator pname for XCode7
[Jira issue](https://issues.apache.org/jira/browse/CB-10918)

CB-10918 Travis tests are failing sometimes for cordova-ios

---

bin/templates/scripts/cordova/lib/build.js

[Jira issue](https://issues.apache.org/jira/browse/CB-10964)

CB-10964 Handle build.json file starting with a BOM

---

CordovaLib/Classes/Public/CDV.h

CDVPlugin.h and CDVPluginResult.h were imported twice.

Remove duplicated #imports

---

bin/templates/scripts/cordova/lib/build.js

self
Fixes a `Error: Cannot read property 'name' of undefined` error when doing an emulate when a target includes a runtime specifier.
1. Created a new project.
2. Did a `cordova emulate ios --target='iPhone-6s, 10.3'` (pass)
3. Did a `cordova emulate ios --target='iPhone-6s'` (pass)
4. Did a `cordova emulate ios` (pass)

CB-12830 - cordova emulate ios with --target throws undefined error

---

.eslintignore

CB-12895 : ignoring cordova.js file

---

CordovaLib/Classes/Public/CDVUserAgentUtil.m

Fix compile error when compile source as objective-c++

Fix compile error when compile source as objective-c++

---

CordovaLib/Classes/Public/CDVCommandDelegate.h
CordovaLib/Classes/Public/CDVCommandDelegateImpl.m

Fix prototype declaration warnings

---

CordovaLib/Classes/Public/CDVViewController.h
CordovaLib/Classes/Public/CDVViewController.m

iOS
Adds an additional clean up step to dealloc

CB-13382 dealloc the webViewEngine

---

.travis.yml
bin/templates/scripts/cordova/lib/check_reqs.js

<!--
self
Update min Xcode requirement to Xcode 9
travis

CB-13921 - Update Xcode requirement to Xcode 9

---

tests/cordova-ios.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
tests/spec/unit/BridgingHeader.spec.js

ios
Add missing license to files.
None

Add Missing ASF License

---

bin/templates/scripts/cordova/lib/check_reqs.js

Tiny change to update the repo URL of `ios-deploy`.

Fix ios-deploy repo in check_reqs

---

package.json

Bump Dev Dependencies to Latest
* jasmine@^3.5.0
* nyc@^15.0.1
* rewire@^5.0.0
- `npm t`

breaking(npm): bump dev dependencies

---

bin/templates/scripts/cordova/lib/prepare.js

Minor lint fix to get tests passing again

Fix eslint failure

---

RELEASENOTES.md

iOS
see issue #1040 & https://github.com/apache/cordova-plugin-inappbrowser/issues/831
closes #1040
see title
N/A

Document breaking changes in 4.3.0 & 4.4.0

---

package-lock.json

ios
closes https://github.com/apache/cordova-ios/issues/1109
Simply a package-lock rebuild.
Ran `npm test` but on a linux machine, so native tests didn't run. Let's hope CI handles the rest.

chore: rebuild package-lock to address reported npm audit vulnerabilities

---

tests/spec/component/versions.spec.js

test(versions): increase test timeout when invoking pod

---

package-lock.json
package.json
tests/spec/unit/Api.spec.js
tests/spec/unit/prepare.spec.js

Use latest Jasmine release
- `npm t`

dep: bump jasmine@^3.10.0

---

.github/workflows/ci.yml

n/a
- Update GitHub Action CI dependencies.
- Resolve codecov failures
Updated:
- `actions/checkout@v3`
- `actions/setup-node@v3`
- `codecov/codecov-action@v3`
n/a

ci(workflow): update dependencies

---

.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md

docs
Not sure if this is present in other repos, but I noticed the current URL is broken here, and found the new one :)

Update Slack signup link in SUPPORT_QUESTION.md

---

CordovaLib/include/Cordova/CDVAvailability.h
package-lock.json
package.json

n/a
Prepare for 7.1.0 release
- Bump package to `7.1.0-dev`
- Update `CDVAvailability` to include `__CORDOVA_7_1_0 70100`
n/a

chore: bump 7.1.0-dev for next minor release

---

tests/spec/unit/fixtures/ios-config-xml/CordovaLib/CordovaLib.xcodeproj/project.pbxproj

While searching for some files I noticed this fixtures file that is very out of date with the original file, so I’ve replaced the old file with the real file.

chore: Update CordovaLib.xcodeproj fixture

---

package-lock.json
package.json

n/a
Prepare for next major release 8.0.0
Bump package.json & package-lock.json
n/a

chore: bump version 8.0.0-dev

---

README.md

iOS
README listed the incorrect Xcode version and incorrect `xcworkspace` file path for 8.x
* Updated the Xcode and node versions
* Corrected the path to the `xcworkspace` file in a generated app
* Added a link to the API docs published on GitHub pages
Previewed in GitHub

chore(readme): Update Xcode/node versions in README

---

.github/workflows/release-audit.yml
.ratignore
licence_checker.yml

Update Release Audit Action & Supporting Files
- Fixed Source Header License formatting
- Updated actions where possible including comments for `apache-rat-action` & `license-checker-action`
- Cleaned up `licence_checker.yml`
- Updated `.ratignore` if needed
- `rat`
- `license-checker`

ci(workflow): update release-audit & license config

---

CordovaLib/Classes/Private/Plugins/CDVStatusBarInternal/CDVStatusBarInternal.h
CordovaLib/Classes/Public/CDVPlugin.m
CordovaLib/CordovaLib.docc/CordovaLib.md
CordovaLib/CordovaLib.docc/upgrading-8.md
CordovaLib/include/Cordova/CDVAppDelegate.h
CordovaLib/include/Cordova/CDVAvailability.h
CordovaLib/include/Cordova/CDVCommandDelegate.h
CordovaLib/include/Cordova/CDVConfigParser.h
CordovaLib/include/Cordova/CDVPlugin+Resources.h
CordovaLib/include/Cordova/CDVPlugin.h
CordovaLib/include/Cordova/CDVPluginNotifications.h
CordovaLib/include/Cordova/CDVPluginResult.h
CordovaLib/include/Cordova/CDVScreenOrientationDelegate.h
CordovaLib/include/Cordova/CDVSettingsDictionary.h
CordovaLib/include/Cordova/CDVTimer.h
CordovaLib/include/Cordova/CDVViewController.h
CordovaLib/include/Cordova/CDVWebViewEngineProtocol.h
CordovaLib/include/Cordova/NSDictionary+CordovaPreferences.h
CordovaLib/include/Cordova/NSMutableArray+QueueAdditions.h

iOS
Improve the DocC API documentation and add annotations for supported versions.
Added and updated doc comments and deprecation notices. Minor reformatting of some pointer types to align with ObjC coding conventions.
All existing tests pass.

docs: Improve API documentation comments
